import type { Contract } from "../contract.ts"
import { atomicWriteFile } from "../normalize.ts"

/**
 * テーマCSSの出力(03-extraction-codegen §6.2 / 06-theming-tailwind §2)。
 *
 * 2026年現在のレジストリでは cssVars はUIアイテムから r/colors/<base>.json に分離しているため、
 * テーマ変数は vendor された colors アイテムから読む。アイテム側に cssVars / css が復活した場合は
 * マージされる(重複排除は完全一致のみ。順序はアイテム名の辞書順で固定)。
 *
 * npm shadcn パッケージ同梱の tailwind.css(カスタムバリアント・scroll-fade・shimmer等)は
 * vendored ファイルを verbatim で取り込む。upstream の実アプリは `@import "shadcn/tailwind.css"`
 * でこの定義群を得るため、手書きで断片を再現しない(欠落がタブのインジケータ消失などの
 * 描画差異になった実績がある — 2026-08)。
 */

export interface ThemeTokens {
  light: Record<string, string>
  dark: Record<string, string>
}

function renderTokenBlock(selector: string, tokens: Record<string, string>, radiusFirst: boolean): string[] {
  const lines: string[] = [`${selector} {`]
  const names = Object.keys(tokens).sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
  const ordered = radiusFirst
    ? [...names.filter((name) => name === "radius"), ...names.filter((name) => name !== "radius")]
    : names
  for (const name of ordered) {
    lines.push(`  --${name}: ${tokens[name]!};`)
  }
  lines.push("}")
  return lines
}

/** テーマトークン ∪ アイテム由来の cssVars(将来のレジストリ形式を考慮)。テーマ側が優先。 */
function mergeThemeTokens(theme: ThemeTokens, contracts: Contract[]): { light: Record<string, string>, dark: Record<string, string> } {
  const light: Record<string, string> = { ...theme.light }
  const dark: Record<string, string> = { ...theme.dark }
  for (const contract of contracts) {
    for (const [name, value] of Object.entries(contract.css_vars.light)) light[name] ??= value
    for (const [name, value] of Object.entries(contract.css_vars.dark)) dark[name] ??= value
  }
  return { light, dark }
}

function renderTokens(theme: ThemeTokens, contracts: Contract[]): string[] {
  const { light, dark } = mergeThemeTokens(theme, contracts)
  return [
    ...renderTokenBlock(":root", light, true),
    ...renderTokenBlock(".dark", dark, false),
  ]
}

/** (4) upstream cssフィールド由来のルール。重複排除は完全一致のみ。 */
function renderCssBlocks(contracts: Contract[]): string[] {
  const lines: string[] = []
  const seen = new Set<string>()
  const cssBlocks = contracts
    .filter((contract) => contract.css.trim().length > 0)
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
  for (const contract of cssBlocks) {
    const css = contract.css.trim()
    if (seen.has(css)) continue
    seen.add(css)
    lines.push("")
    lines.push(`/* from ${contract.name} */`)
    lines.push(css)
  }
  return lines
}

/** (6) ベースレイヤー規則: upstream r/styles/<style> の @layer base 相当。 */
function renderBaseLayer(): string[] {
  // Tailwind v4 の既定ボーダー色は currentColor だが、shadcn はインストール時に
  // この規則を globals.css へ追加して既定を border トークンへ変えている
  return [
    "@layer base {",
    "  * {",
    '    @apply border-border outline-ring/50;',
    "  }",
    "  body {",
    "    @apply bg-background text-foreground;",
    "  }",
    "}",
  ]
}

/** npm shadcn/tailwind.css の verbatim 取り込みブロック。 */
function renderTailwindCssSection(tailwindCss: string): string[] {
  return [
    "/* npm shadcn パッケージ同梱 tailwind.css の verbatim取り込み。upstream 実アプリでは",
    "   `@import \"shadcn/tailwind.css\"` で読まれる定義群(data-* カスタムバリアント、",
    "   accordion キーフレーム、no-scrollbar、scroll-fade、shimmer 等)。手書きで断片を",
    "   再現せず vendor スナップショットから丸ごと取り込む(欠落=描画差異になるため) */",
    tailwindCss.trim(),
  ]
}

/**
 * gem 同梱の shadcn.css。テーマトークン + upstream スタイル共通定義 + ViewComponent
 * 実行時規則。ホストアプリはこのファイルを自分の Tailwind ビルドに読ませる。
 */
export function renderThemeCss(theme: ThemeTokens, contracts: Contract[], style: string, tailwindCss: string): string {
  const lines: string[] = []
  lines.push("/* !! AUTO-GENERATED by tools/extractor — DO NOT EDIT !! */")
  lines.push(`/* Source: shadcn/ui ${style} (manifest: vendor/shadcn/manifest.json) */`)
  lines.push("")
  lines.push("/* (0) アニメーション: upstream r/styles と同じく tw-animate-css を読み込む。")
  lines.push("   animate-in/out・fade/zoom/slide・accordion-down/up 等の実体はここが提供する")
  lines.push("   (npm: tw-animate-css がインストール済みであること) */")
  lines.push('@import "tw-animate-css";')
  lines.push("")
  lines.push("/* (1) ダークモード変換: クラスベース(.dark) */")
  lines.push("@custom-variant dark (&:is(.dark *));")
  lines.push("")
  lines.push("/* (2) semanticトークン(:root = light、.dark = dark): upstream cssVars の統合 */")
  lines.push(...renderTokens(theme, contracts))
  lines.push("")

  // (3) Tailwindテーマへの接続: ユーティリティ(bg-background等)が変数を参照
  lines.push("@theme inline {")
  const light: Record<string, string> = { ...theme.light }
  for (const contract of contracts) {
    for (const name of Object.keys(contract.css_vars.light)) light[name] ??= contract.css_vars.light[name] ?? ""
  }
  for (const name of Object.keys(light).filter((name) => name !== "radius").sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))) {
    lines.push(`  --color-${name}: var(--${name});`)
  }
  if ("radius" in light) {
    lines.push("  --radius-sm: calc(var(--radius) - 4px);")
    lines.push("  --radius-md: calc(var(--radius) - 2px);")
    lines.push("  --radius-lg: var(--radius);")
    lines.push("  --radius-xl: calc(var(--radius) + 4px);")
  }
  lines.push("}")
  lines.push(...renderCssBlocks(contracts))
  lines.push(...renderTailwindCssSection(tailwindCss))

  // (5) ViewComponent実装の実行時規則。閉じたネイティブ dialog / popover は
  // UA由来の display:none よりコンポーネント自身のユーティリティ(.flex等)が
  // 優先されて可視化されるため、同じ規則を作者CSSとして先出ししておく。
  // また collapsible を <details>/<summary> で移植している関係で、summary の
  // 既定マーカー(三角)は upstream(React)側に存在しないため消す
  lines.push("")
  lines.push("/* (5) 実行時規則: 閉じた dialog/popover はユーティリティでも可視化しない */")
  lines.push("dialog:not([open]):not(:popover-open),")
  lines.push("[popover]:not(:popover-open):not(dialog[open]) {")
  lines.push("  display: none;")
  lines.push("}")
  lines.push("")
  lines.push("/* (5) 実行時規則: details 移植コンポーネントの summary マーカーは upstream に無い */")
  lines.push("summary[data-slot='collapsible-trigger']::marker {")
  lines.push("  content: none;")
  lines.push("}")

  // (6) ベースレイヤー規則: upstream r/styles/<style> の @layer base 相当。
  // 本gemはテーマCSS(shadcn.css)をホストへ配るため、ここに含めて同等にする
  // (色指定なし border を持つ Alert / Card 等の枠が本文色になってしまう問題の解消)
  lines.push("")
  lines.push("/* (6) ベースレイヤー: 既定のボーダー色と身体の配色(upstream r/styles 相当) */")
  lines.push(...renderBaseLayer())

  return `${lines.join("\n")}\n`
}

/**
 * visual-parity ハーネス(upstream参照側)の globals。実アプリの globals.css 相当
 * (トークン + @theme + upstream cssフィールド + npm shadcn/tailwind.css + base layer)のみで、
 * gem 固有の実行時規則((5))を含まない。参照側を gem の出力から独立させることで、
 * shadcn.css への移植漏れ・移植ミスが upstream 側との描画差分として検出される
 */
export function renderUpstreamThemeCss(theme: ThemeTokens, contracts: Contract[], style: string, tailwindCss: string): string {
  const lines: string[] = []
  lines.push("/* !! AUTO-GENERATED by tools/extractor — DO NOT EDIT !! */")
  lines.push(`/* Source: shadcn/ui ${style} globals equivalent (manifest: vendor/shadcn/manifest.json) */`)
  lines.push("/* upstream 実アプリの globals.css 相当のみを含む。gem 固有の実行時規則は")
  lines.push("   含まない(参照側を gem 出力から独立させ、移植漏れを差分として検出する) */")
  lines.push("")
  lines.push('@import "tw-animate-css";')
  lines.push("")
  lines.push("@custom-variant dark (&:is(.dark *));")
  lines.push("")
  lines.push(...renderTokens(theme, contracts))
  lines.push("")

  const light: Record<string, string> = { ...theme.light }
  for (const contract of contracts) {
    for (const name of Object.keys(contract.css_vars.light)) light[name] ??= contract.css_vars.light[name] ?? ""
  }
  lines.push("@theme inline {")
  for (const name of Object.keys(light).filter((name) => name !== "radius").sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))) {
    lines.push(`  --color-${name}: var(--${name});`)
  }
  if ("radius" in light) {
    lines.push("  --radius-sm: calc(var(--radius) - 4px);")
    lines.push("  --radius-md: calc(var(--radius) - 2px);")
    lines.push("  --radius-lg: var(--radius);")
    lines.push("  --radius-xl: calc(var(--radius) + 4px);")
  }
  lines.push("}")
  lines.push(...renderCssBlocks(contracts))
  lines.push(...renderTailwindCssSection(tailwindCss))
  lines.push("")
  lines.push(...renderBaseLayer())

  return `${lines.join("\n")}\n`
}

export async function emitThemeCss(theme: ThemeTokens, contracts: Contract[], cssFile: string, style: string, tailwindCss: string): Promise<string> {
  await atomicWriteFile(cssFile, renderThemeCss(theme, contracts, style, tailwindCss))
  return cssFile
}

export async function emitUpstreamThemeCss(theme: ThemeTokens, contracts: Contract[], cssFile: string, style: string, tailwindCss: string): Promise<string> {
  await atomicWriteFile(cssFile, renderUpstreamThemeCss(theme, contracts, style, tailwindCss))
  return cssFile
}
