import type { Contract } from "../contract.ts"
import { atomicWriteFile } from "../normalize.ts"

/**
 * app/assets/stylesheets/shadcn/shadcn.css の出力(03-extraction-codegen §6.2 / 06-theming-tailwind §2)。
 *
 * 2026年現在のレジストリでは cssVars はUIアイテムから r/colors/<base>.json に分離しているため、
 * テーマ変数は vendor された colors アイテムから読む。アイテム側に cssVars / css が復活した場合は
 * マージされる(重複排除は完全一致のみ。順序はアイテム名の辞書順で固定)。
 */

export interface ThemeTokens {
  light: Record<string, string>
  dark: Record<string, string>
}

function renderTokenBlock(selector: string, tokens: Record<string, string>, radiusFirst: boolean): string[] {
  const lines: string[] = [`${selector} {`]
  const names = Object.keys(tokens).sort((a, b) => a.localeCompare(b))
  const ordered = radiusFirst
    ? [...names.filter((name) => name === "radius"), ...names.filter((name) => name !== "radius")]
    : names
  for (const name of ordered) {
    lines.push(`  --${name}: ${tokens[name]!};`)
  }
  lines.push("}")
  return lines
}

export function renderThemeCss(theme: ThemeTokens, contracts: Contract[]): string {
  const light: Record<string, string> = { ...theme.light }
  const dark: Record<string, string> = { ...theme.dark }
  // アイテム由来の cssVars(将来のレジストリ形式を考慮)。テーマ側が優先。
  for (const contract of contracts) {
    for (const [name, value] of Object.entries(contract.css_vars.light)) light[name] ??= value
    for (const [name, value] of Object.entries(contract.css_vars.dark)) dark[name] ??= value
  }

  const lines: string[] = []
  lines.push("/* !! AUTO-GENERATED by tools/extractor — DO NOT EDIT !! */")
  lines.push("/* Source: shadcn/ui new-york-v4 (manifest: vendor/shadcn/manifest.json) */")
  lines.push("")
  lines.push("/* (1) ダークモード変換: クラスベース(.dark) */")
  lines.push("@custom-variant dark (&:is(.dark *));")
  lines.push("")
  lines.push("/* (2) semanticトークン(:root = light、.dark = dark): upstream cssVars の統合 */")
  lines.push(...renderTokenBlock(":root", light, true))
  lines.push(...renderTokenBlock(".dark", dark, false))
  lines.push("")

  // (3) Tailwindテーマへの接続: ユーティリティ(bg-background等)が変数を参照
  lines.push("@theme inline {")
  for (const name of Object.keys(light).filter((name) => name !== "radius").sort((a, b) => a.localeCompare(b))) {
    lines.push(`  --color-${name}: var(--${name});`)
  }
  if ("radius" in light) {
    lines.push("  --radius-sm: calc(var(--radius) - 4px);")
    lines.push("  --radius-md: calc(var(--radius) - 2px);")
    lines.push("  --radius-lg: var(--radius);")
    lines.push("  --radius-xl: calc(var(--radius) + 4px);")
  }
  lines.push("}")

  // (4) upstream cssフィールド由来のルール。重複排除は完全一致のみ。
  const seen = new Set<string>()
  const cssBlocks = contracts
    .filter((contract) => contract.css.trim().length > 0)
    .sort((a, b) => a.name.localeCompare(b.name))
  for (const contract of cssBlocks) {
    const css = contract.css.trim()
    if (seen.has(css)) continue
    seen.add(css)
    lines.push("")
    lines.push(`/* from ${contract.name} */`)
    lines.push(css)
  }

  return `${lines.join("\n")}\n`
}

export async function emitThemeCss(theme: ThemeTokens, contracts: Contract[], cssFile: string): Promise<string> {
  await atomicWriteFile(cssFile, renderThemeCss(theme, contracts))
  return cssFile
}
