import type { Contract } from "../contract.ts"
import { atomicWriteFile } from "../normalize.ts"

/**
 * app/assets/stylesheets/shadcn/shadcn.css の出力(03-extraction-codegen §6.2 / 06-theming-tailwind §2)。
 *
 * 2026年現在のレジストリでは cssVars はUIアイテムから r/colors/<base>.json に分離しているため、
 * テーマ変数は vendor された colors アイテムから読む。アイテム側に cssVars / css が復活した場合は
 * マージされる(重複排除は完全一致のみ。順序はアイテム名の辞書順で固定)。
 */

export interface ThemeTokens {
  light: Record<string, string>
  dark: Record<string, string>
}

function renderTokenBlock(selector: string, tokens: Record<string, string>, radiusFirst: boolean): string[] {
  const lines: string[] = [`${selector} {`]
  const names = Object.keys(tokens).sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
  const ordered = radiusFirst
    ? [...names.filter((name) => name === "radius"), ...names.filter((name) => name !== "radius")]
    : names
  for (const name of ordered) {
    lines.push(`  --${name}: ${tokens[name]!};`)
  }
  lines.push("}")
  return lines
}

export function renderThemeCss(theme: ThemeTokens, contracts: Contract[], style: string): string {
  const light: Record<string, string> = { ...theme.light }
  const dark: Record<string, string> = { ...theme.dark }
  // アイテム由来の cssVars(将来のレジストリ形式を考慮)。テーマ側が優先。
  for (const contract of contracts) {
    for (const [name, value] of Object.entries(contract.css_vars.light)) light[name] ??= value
    for (const [name, value] of Object.entries(contract.css_vars.dark)) dark[name] ??= value
  }

  const lines: string[] = []
  lines.push("/* !! AUTO-GENERATED by tools/extractor — DO NOT EDIT !! */")
  lines.push(`/* Source: shadcn/ui ${style} (manifest: vendor/shadcn/manifest.json) */`)
  lines.push("")
  lines.push("/* (0) アニメーション: upstream r/styles と同じく tw-animate-css を読み込む。")
  lines.push("   animate-in/out・fade/zoom/slide・accordion-down/up 等の実体はここが提供する")
  lines.push("   (npm: tw-animate-css がインストール済みであること) */")
  lines.push('@import "tw-animate-css";')
  lines.push("")
  lines.push("/* (1) ダークモード変換: クラスベース(.dark) */")
  lines.push("@custom-variant dark (&:is(.dark *));")
  lines.push("")
  lines.push("/* (1b) 方向バリアント: upstream npm shadcn/tailwind.css 由来。")
  lines.push("   契約の data-horizontal: / data-vertical: は data-orientation 属性値に")
  lines.push("   対応する(tailwind 既定の属性存在マッチのままでは data-orientation に")
  lines.push("   絶対に合わず、tabs の active インジケータ等が描画されない)。")
  lines.push("   upstream 同ファイルには他に data-open/checked/selected 等のバリアントや")
  lines.push("   scroll-fade・shimmer ユーティリティがあるが未移植(必要になった属性は")
  lines.push("   コンポーネント側で bare 属性を出す state_attrs.js 等で代替済み) */")
  lines.push('@custom-variant data-horizontal (&:where([data-orientation="horizontal"]));')
  lines.push('@custom-variant data-vertical (&:where([data-orientation="vertical"]));')
  lines.push("")
  lines.push("/* (2) semanticトークン(:root = light、.dark = dark): upstream cssVars の統合 */")
  lines.push(...renderTokenBlock(":root", light, true))
  lines.push(...renderTokenBlock(".dark", dark, false))
  lines.push("")

  // (3) Tailwindテーマへの接続: ユーティリティ(bg-background等)が変数を参照
  lines.push("@theme inline {")
  for (const name of Object.keys(light).filter((name) => name !== "radius").sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))) {
    lines.push(`  --color-${name}: var(--${name});`)
  }
  if ("radius" in light) {
    lines.push("  --radius-sm: calc(var(--radius) - 4px);")
    lines.push("  --radius-md: calc(var(--radius) - 2px);")
    lines.push("  --radius-lg: var(--radius);")
    lines.push("  --radius-xl: calc(var(--radius) + 4px);")
  }
  lines.push("}")

  // (4) upstream cssフィールド由来のルール。重複排除は完全一致のみ。
  const seen = new Set<string>()
  const cssBlocks = contracts
    .filter((contract) => contract.css.trim().length > 0)
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
  for (const contract of cssBlocks) {
    const css = contract.css.trim()
    if (seen.has(css)) continue
    seen.add(css)
    lines.push("")
    lines.push(`/* from ${contract.name} */`)
    lines.push(css)
  }

  // (5) ViewComponent実装の実行時規則。閉じたネイティブ dialog / popover は
  // UA由来の display:none よりコンポーネント自身のユーティリティ(.flex等)が
  // 優先されて可視化されるため、同じ規則を作者CSSとして先出ししておく。
  // また collapsible を <details>/<summary> で移植している関係で、summary の
  // 既定マーカー(三角)は upstream(React)側に存在しないため消す
  lines.push("")
  lines.push("/* (5) 実行時規則: 閉じた dialog/popover はユーティリティでも可視化しない */")
  lines.push("dialog:not([open]):not(:popover-open),")
  lines.push("[popover]:not(:popover-open):not(dialog[open]) {")
  lines.push("  display: none;")
  lines.push("}")
  lines.push("")
  lines.push("/* (5) 実行時規則: details 移植コンポーネントの summary マーカーは upstream に無い */")
  lines.push("summary[data-slot='collapsible-trigger']::marker {")
  lines.push("  content: none;")
  lines.push("}")

  // (6) ベースレイヤー規則: upstream r/styles/<style> の @layer base 相当。
  // Tailwind v4 の既定ボーダー色は currentColor だが、shadcn はインストール時に
  // この規則を globals.css へ追加して既定を border トークンへ変えている。
  // 本gemはテーマCSS(shadcn.css)をホストへ配るため、ここに含めて同等にする
  // (色指定なし border を持つ Alert / Card 等の枠が本文色になってしまう問題の解消)
  lines.push("")
  lines.push("/* (6) ベースレイヤー: 既定のボーダー色と身体の配色(upstream r/styles 相当) */")
  lines.push("@layer base {")
  lines.push("  * {")
  lines.push("    @apply border-border outline-ring/50;")
  lines.push("  }")
  lines.push("  body {")
  lines.push("    @apply bg-background text-foreground;")
  lines.push("  }")
  lines.push("}")

  return `${lines.join("\n")}\n`
}

export async function emitThemeCss(theme: ThemeTokens, contracts: Contract[], cssFile: string, style: string): Promise<string> {
  await atomicWriteFile(cssFile, renderThemeCss(theme, contracts, style))
  return cssFile
}
