# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `css_parser` gem.
# Please instead update this file by running `bin/tapioca gem css_parser`.


# pkg:gem/css_parser#lib/css_parser/version.rb:3
module CssParser
  class << self
    # Calculates the specificity of a CSS selector
    # per http://www.w3.org/TR/CSS21/cascade.html#specificity
    #
    # Returns an integer.
    #
    # ==== Example
    #  CssParser.calculate_specificity('#content div p:first-line a:link')
    #  => 114
    # --
    # Thanks to Rafael Salazar and Nick Fitzsimons on the css-discuss list for their help.
    # ++
    #
    # pkg:gem/css_parser#lib/css_parser.rb:108
    def calculate_specificity(selector); end

    # Make <tt>url()</tt> links absolute.
    #
    # Takes a block of CSS and returns it with all relative URIs converted to absolute URIs.
    #
    # "For CSS style sheets, the base URI is that of the style sheet, not that of the source document."
    # per http://www.w3.org/TR/CSS21/syndata.html#uri
    #
    # Returns a string.
    #
    # ==== Example
    #  CssParser.convert_uris("body { background: url('../style/yellow.png?abc=123') };",
    #               "http://example.org/style/basic.css").inspect
    #  => "body { background: url('http://example.org/style/yellow.png?abc=123') };"
    #
    # pkg:gem/css_parser#lib/css_parser.rb:132
    def convert_uris(css, base_uri); end

    # Merge multiple CSS RuleSets by cascading according to the CSS 2.1 cascading rules
    # (http://www.w3.org/TR/REC-CSS2/cascade.html#cascading-order).
    #
    # Takes one or more RuleSet objects.
    #
    # Returns a RuleSet.
    #
    # ==== Cascading
    # If a RuleSet object has its +specificity+ defined, that specificity is
    # used in the cascade calculations.
    #
    # If no specificity is explicitly set and the RuleSet has *one* selector,
    # the specificity is calculated using that selector.
    #
    # If no selectors the specificity is treated as 0.
    #
    # If multiple selectors are present then the greatest specificity is used.
    #
    # ==== Example #1
    #   rs1 = RuleSet.new(nil, 'color: black;')
    #   rs2 = RuleSet.new(nil, 'margin: 0px;')
    #
    #   merged = CssParser.merge(rs1, rs2)
    #
    #   puts merged
    #   => "{ margin: 0px; color: black; }"
    #
    # ==== Example #2
    #   rs1 = RuleSet.new(nil, 'background-color: black;')
    #   rs2 = RuleSet.new(nil, 'background-image: none;')
    #
    #   merged = CssParser.merge(rs1, rs2)
    #
    #   puts merged
    #   => "{ background: none black; }"
    # --
    # TODO: declaration_hashes should be able to contain a RuleSet
    #       this should be a Class method
    #
    # pkg:gem/css_parser#lib/css_parser.rb:53
    def merge(*rule_sets); end

    # pkg:gem/css_parser#lib/css_parser/regexps.rb:4
    def regex_possible_values(*values); end

    # pkg:gem/css_parser#lib/css_parser.rb:149
    def sanitize_media_query(raw); end
  end
end

# Special units
#
# pkg:gem/css_parser#lib/css_parser/regexps.rb:53
CssParser::BOX_MODEL_UNITS_RX = T.let(T.unsafe(nil), Regexp)

# Exception class used if a request is made to load a CSS file more than once.
#
# pkg:gem/css_parser#lib/css_parser/parser.rb:10
class CssParser::CircularReferenceError < ::StandardError; end

# pkg:gem/css_parser#lib/css_parser/regexps.rb:98
CssParser::ELEMENTS_AND_PSEUDO_ELEMENTS_RX_NC = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:59
CssParser::FONT_UNITS_RX = T.let(T.unsafe(nil), Regexp)

# RE_AT_IMPORT_RULE = Regexp.new('@import[\s]*(' + RE_STRING.to_s + ')([\w\s\,]*)[;]?', Regexp::IGNORECASE) -- should handle url() even though it is not allowed
# ++
#
# pkg:gem/css_parser#lib/css_parser/regexps.rb:36
CssParser::IMPORTANT_IN_PROPERTY_RX = T.let(T.unsafe(nil), Regexp)

# Colours
#
# pkg:gem/css_parser#lib/css_parser/regexps.rb:109
CssParser::NAMED_COLOURS = T.let(T.unsafe(nil), Array)

# Patterns for specificity calculations
#
# pkg:gem/css_parser#lib/css_parser/regexps.rb:80
CssParser::NON_ID_ATTRIBUTES_AND_PSEUDO_CLASSES_RX_NC = T.let(T.unsafe(nil), Regexp)

# == Parser class
#
# All CSS is converted to UTF-8.
#
# When calling Parser#new there are some configuaration options:
# [<tt>absolute_paths</tt>] Convert relative paths to absolute paths (<tt>href</tt>, <tt>src</tt> and <tt>url('')</tt>. Boolean, default is <tt>false</tt>.
# [<tt>import</tt>] Follow <tt>@import</tt> rules. Boolean, default is <tt>true</tt>.
# [<tt>io_exceptions</tt>] Throw an exception if a link can not be found. Boolean, default is <tt>true</tt>.
# [<tt>allow_local_network</tt>] Permit http(s) fetches against loopback / private / link-local / cloud-metadata addresses. Boolean, default is <tt>false</tt>. When <tt>false</tt> (the default), outbound HTTP requests are routed through <tt>ssrf_filter</tt>, which resolves the host and rejects unsafe IP ranges. Set to <tt>true</tt> only when the destination is known to be safe (e.g. local fixture servers in tests). Independent of <tt>allow_file_uris</tt>.
# [<tt>allow_file_uris</tt>] Permit <tt>file://</tt> URIs via <tt>load_uri!</tt>. Boolean, default is <tt>false</tt>. When <tt>false</tt> (the default), a caller that passes a <tt>file://</tt> URI to <tt>load_uri!</tt> — directly or via a CSS <tt>@import</tt> resolved against a <tt>file://</tt> base_uri — is refused, closing the local-file-disclosure vector when the URI is influenced by user input. <tt>load_file!</tt> is unaffected: it is the explicit local-file API and takes a caller-supplied path. Independent of <tt>allow_local_network</tt>.
#
# pkg:gem/css_parser#lib/css_parser/parser.rb:22
class CssParser::Parser
  # pkg:gem/css_parser#lib/css_parser/parser.rb:43
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/css_parser#lib/css_parser/parser.rb:88
  def [](selector, media_types = T.unsafe(nil)); end

  # Add a raw block of CSS.
  #
  # In order to follow +@import+ rules you must supply either a
  # +:base_dir+ or +:base_uri+ option.
  #
  # Use the +:media_types+ option to set the media type(s) for this block.  Takes an array of symbols.
  #
  # Use the +:only_media_types+ option to selectively follow +@import+ rules.  Takes an array of symbols.
  #
  # ==== Example
  #   css = <<-EOT
  #     body { font-size: 10pt }
  #     p { margin: 0px; }
  #     @media screen, print {
  #       body { line-height: 1.2 }
  #     }
  #   EOT
  #
  #   parser = CssParser::Parser.new
  #   parser.add_block!(css)
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:126
  def add_block!(block, options = T.unsafe(nil)); end

  # Add a CSS rule by setting the +selectors+, +declarations+
  # and +media_types+. Optional pass +filename+ , +offset+ for source
  # reference too.
  #
  # +media_types+ can be a symbol or an array of symbols. default to :all
  # optional fields for source location for source location
  # +filename+ can be a string or uri pointing to the file or url location.
  # +offset+ should be Range object representing the start and end byte locations where the rule was found in the file.
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:181
  def add_rule!(*args, selectors: T.unsafe(nil), block: T.unsafe(nil), filename: T.unsafe(nil), offset: T.unsafe(nil), media_types: T.unsafe(nil)); end

  # Add a CssParser RuleSet object.
  #
  # +media_types+ can be a symbol or an array of symbols.
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:229
  def add_rule_set!(ruleset, media_types = T.unsafe(nil)); end

  # Add a CSS rule by setting the +selectors+, +declarations+, +filename+, +offset+ and +media_types+.
  #
  # +filename+ can be a string or uri pointing to the file or url location.
  # +offset+ should be Range object representing the start and end byte locations where the rule was found in the file.
  # +media_types+ can be a symbol or an array of symbols.
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:218
  def add_rule_with_offsets!(selectors, declarations, filename, offset, media_types = T.unsafe(nil)); end

  # Merge declarations with the same selector.
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:347
  def compact!; end

  # Iterate through RuleSet objects.
  #
  # +media_types+ can be a symbol or an array of symbols.
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:254
  def each_rule_set(media_types = T.unsafe(nil)); end

  # Iterate through CSS selectors.
  #
  # +media_types+ can be a symbol or an array of symbols.
  # See RuleSet#each_selector for +options+.
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:290
  def each_selector(all_media_types = T.unsafe(nil), options = T.unsafe(nil)); end

  # Get declarations by selector.
  #
  # +media_types+ are optional, and can be a symbol or an array of symbols.
  # The default value is <tt>:all</tt>.
  #
  # ==== Examples
  #  find_by_selector('#content')
  #  => 'font-size: 13px; line-height: 1.2;'
  #
  #  find_by_selector('#content', [:screen, :handheld])
  #  => 'font-size: 13px; line-height: 1.2;'
  #
  #  find_by_selector('#content', :print)
  #  => 'font-size: 11pt; line-height: 1.2;'
  #
  # Returns an array of declarations.
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:81
  def find_by_selector(selector, media_types = T.unsafe(nil)); end

  # Finds the rule sets that match the given selectors
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:91
  def find_rule_sets(selectors, media_types = T.unsafe(nil)); end

  # Load a local CSS file.
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:549
  def load_file!(file_name, options = T.unsafe(nil), deprecated = T.unsafe(nil)); end

  # Load a local CSS string.
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:574
  def load_string!(src, options = T.unsafe(nil), deprecated = T.unsafe(nil)); end

  # Load a remote CSS file.
  #
  # You can also pass in file://test.css
  #
  # See add_block! for options.
  #
  # Deprecated: originally accepted three params: `uri`, `base_uri` and `media_types`
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:498
  def load_uri!(uri, options = T.unsafe(nil), deprecated = T.unsafe(nil)); end

  # Array of CSS files that have been loaded.
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:41
  def loaded_uris; end

  # pkg:gem/css_parser#lib/css_parser/parser.rb:351
  def parse_block_into_rule_sets!(block, options = T.unsafe(nil)); end

  # Remove a CssParser RuleSet object.
  #
  # +media_types+ can be a symbol or an array of symbols.
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:241
  def remove_rule_set!(ruleset, media_types = T.unsafe(nil)); end

  # A hash of { :media_query => rule_sets }
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:332
  def rules_by_media_query; end

  # Output all CSS rules as a Hash
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:266
  def to_h(which_media = T.unsafe(nil)); end

  # Output all CSS rules as a single stylesheet.
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:301
  def to_s(which_media = T.unsafe(nil)); end

  protected

  # Check that a path hasn't been loaded already
  #
  # Raises a CircularReferenceError exception if io_exceptions are on,
  # otherwise returns true/false.
  # TODO: fix rubocop
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:596
  def circular_reference_check(path); end

  # Strip comments and clean up blank lines from a block of CSS.
  #
  # Returns a string.
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:622
  def cleanup_block(block, options = T.unsafe(nil)); end

  # Net::HTTP path used only when `allow_local_network: true`. Validates
  # the URI scheme on every redirect hop so a `Location: file://...`
  # cannot be followed even on this opt-in code path.
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:729
  def fetch_via_net_http(uri, redirect_count = T.unsafe(nil)); end

  # Remove a pattern from a given string
  #
  # Returns a string.
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:611
  def ignore_pattern(css, regex, options); end

  # Read a local file:// URI. Called only from `load_uri!` — never
  # from the remote read path — so an HTTP redirect cannot reach this
  # branch (GHSA-9pmc-p236-855h).
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:640
  def read_local_file(uri); end

  # Download a remote http(s) file into a string.
  #
  # Returns the file's data and character set in an array.
  #
  # In the default (secure) configuration, requests are issued via
  # `SsrfFilter.get`, which:
  #   - rejects any scheme other than http/https (defeats redirect-to-
  #     `file://` / `gopher://` / `dict://` etc.);
  #   - resolves the hostname with `Resolv` and rejects requests whose
  #     resolved IP is loopback, RFC-1918, link-local, multicast, or any
  #     other range typically used for internal services (defeats SSRF
  #     via literal IPs and via CNAME / attacker-controlled A records);
  #   - re-validates scheme and IP on every redirect hop.
  #
  # When `allow_local_network: true` is set on the Parser, the SSRF
  # check is bypassed and plain `Net::HTTP` is used — but the scheme
  # is still validated on every redirect hop, so cross-scheme
  # redirect to `file://` (the original GHSA-9pmc-p236-855h sink)
  # remains closed even on this opt-in path.
  # --
  # TODO: add option to fail silently or throw and exception on a 404
  # ++
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:683
  def read_remote_file(uri); end

  private

  # recurse through nested nodes and return them as Hashes nested in
  # passed hash
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:778
  def css_node_to_h(hash, key, val); end

  # Retrieve a folded declaration block from the internal cache.
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:765
  def get_folded_declaration(block_hash); end

  # pkg:gem/css_parser#lib/css_parser/parser.rb:769
  def reset!; end

  # Save a folded declaration block to the internal cache.
  #
  # pkg:gem/css_parser#lib/css_parser/parser.rb:760
  def save_folded_declaration(block_hash, folded_declaration); end
end

# pkg:gem/css_parser#lib/css_parser/parser.rb:31
CssParser::Parser::MAX_REDIRECTS = T.let(T.unsafe(nil), Integer)

# Schemes accepted by `read_remote_file`. `file://` is intentionally
# NOT in this list — local files are handled directly by `load_uri!`
# and `load_file!`. Keeping `file://` out of the remote read path
# closes the cross-scheme redirect (HTTP 3xx → `file://`) vector that
# was GHSA-9pmc-p236-855h.
#
# pkg:gem/css_parser#lib/css_parser/parser.rb:38
CssParser::Parser::REMOTE_ALLOWED_SCHEMES = T.let(T.unsafe(nil), Array)

# Initial parsing
#
# pkg:gem/css_parser#lib/css_parser/parser.rb:29
CssParser::Parser::RE_AT_IMPORT_RULE = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/parser.rb:24
CssParser::Parser::RULESET_TOKENIZER_RX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/parser.rb:25
CssParser::Parser::STRIP_CSS_COMMENTS_RX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/parser.rb:26
CssParser::Parser::STRIP_HTML_COMMENTS_RX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/parser.rb:23
CssParser::Parser::USER_AGENT = T.let(T.unsafe(nil), String)

# Initial parsing
#
# pkg:gem/css_parser#lib/css_parser/regexps.rb:29
CssParser::RE_AT_IMPORT_RULE = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:57
CssParser::RE_BACKGROUND_POSITION = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:58
CssParser::RE_BACKGROUND_SIZE = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:60
CssParser::RE_BORDER_STYLE = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:61
CssParser::RE_BORDER_UNITS = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:268
CssParser::RE_COLOUR = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:266
CssParser::RE_COLOUR_HEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:267
CssParser::RE_COLOUR_NAMED = T.let(T.unsafe(nil), Regexp)

# CSS <number> allows the integer part to be omitted (e.g. `.1`), per CSS Values & Units.
# `(?:\d*\.)?\d+` accepts `1`, `1.5`, and `.5` while still rejecting bare `1.`.
#
# pkg:gem/css_parser#lib/css_parser/regexps.rb:264
CssParser::RE_COLOUR_NUMERIC = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:265
CssParser::RE_COLOUR_NUMERIC_ALPHA = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:13
CssParser::RE_ESCAPE = T.let(T.unsafe(nil), Regexp)

# Functions like calc, var, clamp, etc.
#
# pkg:gem/css_parser#lib/css_parser/regexps.rb:64
CssParser::RE_FUNCTIONS = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:26
CssParser::RE_GRADIENT = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:14
CssParser::RE_IDENT = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:47
CssParser::RE_IMAGE = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:21
CssParser::RE_INHERIT = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:38
CssParser::RE_INSIDE_OUTSIDE = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:54
CssParser::RE_LENGTH_OR_PERCENTAGE = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:41
CssParser::RE_LIST_STYLE_TYPE = T.let(T.unsafe(nil), Regexp)

# :stopdoc:
# Base types
#
# pkg:gem/css_parser#lib/css_parser/regexps.rb:10
CssParser::RE_NL = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:11
CssParser::RE_NON_ASCII = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:40
CssParser::RE_REPEAT = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:39
CssParser::RE_SCROLL_FIXED = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:55
CssParser::RE_SINGLE_BACKGROUND_POSITION = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:56
CssParser::RE_SINGLE_BACKGROUND_SIZE = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:19
CssParser::RE_STRING = T.let(T.unsafe(nil), Regexp)

# General strings
#
# pkg:gem/css_parser#lib/css_parser/regexps.rb:17
CssParser::RE_STRING1 = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:18
CssParser::RE_STRING2 = T.let(T.unsafe(nil), Regexp)

# [^\0-\177]
#
# pkg:gem/css_parser#lib/css_parser/regexps.rb:12
CssParser::RE_UNICODE = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:23
CssParser::RE_URI = T.let(T.unsafe(nil), Regexp)

# Exception class used for any errors encountered while downloading remote files.
#
# pkg:gem/css_parser#lib/css_parser/parser.rb:7
class CssParser::RemoteFileError < ::IOError; end

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:6
class CssParser::RuleSet
  extend ::Forwardable

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:257
  def initialize(*args, selectors: T.unsafe(nil), block: T.unsafe(nil), offset: T.unsafe(nil), filename: T.unsafe(nil), specificity: T.unsafe(nil)); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:299
  def [](property); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:254
  def []=(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:253
  def add_declaration!(*_arg0, **_arg1, &_arg2); end

  # Looks for long format CSS background properties (e.g. <tt>background-color</tt>) and
  # converts them into a shorthand CSS <tt>background</tt> property.
  #
  # Leaves properties declared !important alone.
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:544
  def create_background_shorthand!; end

  # Combine border-color, border-style and border-width into border
  # Should be run after create_dimensions_shorthand!
  #
  # TODO: this is extremely similar to create_background_shorthand! and should be combined
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:561
  def create_border_shorthand!; end

  # Looks for long format CSS dimensional properties (margin, padding, border-color, border-style and border-width)
  # and converts them into shorthand CSS properties.
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:583
  def create_dimensions_shorthand!; end

  # Looks for long format CSS font properties (e.g. <tt>font-weight</tt>) and
  # tries to convert them into a shorthand CSS <tt>font</tt> property.  All
  # font properties must be present in order to create a shorthand declaration.
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:607
  def create_font_shorthand!; end

  # Looks for long format CSS list-style properties (e.g. <tt>list-style-type</tt>) and
  # converts them into a shorthand CSS <tt>list-style</tt> property.
  #
  # Leaves properties declared !important alone.
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:634
  def create_list_style_shorthand!; end

  # Create shorthand declarations (e.g. +margin+ or +font+) whenever possible.
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:510
  def create_shorthand!; end

  # Combine several properties into a shorthand one
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:520
  def create_shorthand_properties!(properties, shorthand_property); end

  # Return all declarations as a string.
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:327
  def declarations_to_s(options = T.unsafe(nil)); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:253
  def delete(*_arg0, **_arg1, &_arg2); end

  # Iterate through declarations.
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:320
  def each_declaration; end

  # Iterate through selectors.
  #
  # Options
  # -  +force_important+ -- boolean
  #
  # ==== Example
  #   ruleset.each_selector do |sel, dec, spec|
  #     ...
  #   end
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:310
  def each_selector(options = T.unsafe(nil)); end

  # Convert shorthand background declarations (e.g. <tt>background: url("chess.png") gray 50% repeat fixed;</tt>)
  # into their constituent parts.
  #
  # See http://www.w3.org/TR/CSS21/colors.html#propdef-background
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:350
  def expand_background_shorthand!; end

  # Split shorthand border declarations (e.g. <tt>border: 1px red;</tt>)
  # Additional splitting happens in expand_dimensions_shorthand!
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:380
  def expand_border_shorthand!; end

  # Split shorthand dimensional declarations (e.g. <tt>margin: 0px auto;</tt>)
  # into their constituent parts.  Handles margin, padding, border-color, border-style and border-width.
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:398
  def expand_dimensions_shorthand!; end

  # Convert shorthand font declarations (e.g. <tt>font: 300 italic 11px/14px verdana, helvetica, sans-serif;</tt>)
  # into their constituent parts.
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:435
  def expand_font_shorthand!; end

  # Convert shorthand list-style declarations (e.g. <tt>list-style: lower-alpha outside;</tt>)
  # into their constituent parts.
  #
  # See http://www.w3.org/TR/CSS21/generate.html#lists
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:490
  def expand_list_style_shorthand!; end

  # Split shorthand declarations (e.g. +margin+ or +font+) into their constituent parts.
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:337
  def expand_shorthand!; end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:372
  def extract_background_size_from(value); end

  # the local or remote location
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:241
  def filename; end

  # the local or remote location
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:241
  def filename=(_arg0); end

  # Get the value of a property
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:294
  def get_value(property); end

  # optional field for storing source reference
  # File offset range
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:239
  def offset; end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:255
  def remove_declaration!(*_arg0, **_arg1, &_arg2); end

  # Array of selector strings.
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:244
  def selectors; end

  # Integer with the specificity to use for this RuleSet.
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:247
  def specificity; end

  # Integer with the specificity to use for this RuleSet.
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:247
  def specificity=(_arg0); end

  # Return the CSS rule set as a string.
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:332
  def to_s; end

  private

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:642
  def compute_dimensions_shorthand(values); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:640
  def declarations; end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:640
  def declarations=(_arg0); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:655
  def parse_declarations!(block); end

  # --
  # TODO: way too simplistic
  # ++
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:690
  def parse_selectors!(selectors); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:698
  def split_value_preserving_function_whitespace(value); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:683
  def unmatched_open_parenthesis?(declarations); end
end

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:11
CssParser::RuleSet::BACKGROUND_PROPERTIES = T.let(T.unsafe(nil), Array)

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:16
CssParser::RuleSet::BORDER_PROPERTIES = T.let(T.unsafe(nil), Array)

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:15
CssParser::RuleSet::BORDER_STYLE_PROPERTIES = T.let(T.unsafe(nil), Array)

# Tokens for parse_declarations!
#
# pkg:gem/css_parser#lib/css_parser/rule_set.rb:32
CssParser::RuleSet::COLON = T.let(T.unsafe(nil), String)

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:21
CssParser::RuleSet::DIMENSIONS = T.let(T.unsafe(nil), Array)

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:17
CssParser::RuleSet::DIMENSION_DIRECTIONS = T.let(T.unsafe(nil), Array)

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:37
class CssParser::RuleSet::Declarations
  extend ::Forwardable

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:71
  def initialize(declarations = T.unsafe(nil)); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:214
  def ==(other); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:112
  def [](property); end

  # Add a CSS declaration
  # @param [#to_s] property that should be added
  # @param [Value, #to_s] value of the property
  #
  # @example
  #   declarations['color'] = 'blue'
  #
  #   puts declarations['color']
  #   => #<CssParser::RuleSet::Declarations::Value:0x000000000305c730 @important=false, @order=1, @value="blue">
  #
  # @example
  #   declarations['margin'] = '0px auto !important'
  #
  #   puts declarations['margin']
  #   => #<CssParser::RuleSet::Declarations::Value:0x00000000030c1838 @important=true, @order=2, @value="0px auto">
  #
  # If the property already exists its value will be over-written unless it was !important and the new value
  # is not !important.
  # If the value is empty - property will be deleted
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:95
  def []=(property, value); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:110
  def add_declaration!(property, value); end

  # Remove CSS declaration
  # @param [#to_s] property property to be removed
  #
  # @example
  #   declarations.delete('color')
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:130
  def delete(property); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:69
  def each(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:69
  def each_value(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:115
  def get_value(property); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:117
  def key?(property); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:133
  def remove_declaration!(property); end

  # Replace CSS property with multiple declarations
  # @param [#to_s] property property name to be replaces
  # @param [Hash<String => [String, Value]>] replacements hash with properties to replace with
  #
  # @example
  #  declarations = Declarations.new('line-height' => '0.25px', 'font' => 'small-caps', 'font-size' => '12em')
  #  declarations.replace_declaration!('font', {'line-height' => '1px', 'font-variant' => 'small-caps', 'font-size' => '24px'})
  #  declarations
  #  => #<CssParser::RuleSet::Declarations:0x00000000029c3018
  #  @declarations=
  #  {"line-height"=>#<CssParser::RuleSet::Declarations::Value:0x00000000038ac458 @important=false, @value="1px">,
  #   "font-variant"=>#<CssParser::RuleSet::Declarations::Value:0x00000000039b3ec8 @important=false, @value="small-caps">,
  #   "font-size"=>#<CssParser::RuleSet::Declarations::Value:0x00000000029c2c80 @important=false, @value="12em">}>
  #
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:148
  def replace_declaration!(property, replacements, preserve_importance: T.unsafe(nil)); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:121
  def size; end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:203
  def to_s(options = T.unsafe(nil)); end

  protected

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:222
  def declarations; end

  private

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:226
  def declarations=(_arg0); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:228
  def normalize_property(property); end
end

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:38
class CssParser::RuleSet::Declarations::Value
  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:42
  def initialize(value, important: T.unsafe(nil)); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:60
  def ==(other); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:40
  def important; end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:40
  def important=(_arg0); end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:56
  def to_s; end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:39
  def value; end

  # pkg:gem/css_parser#lib/css_parser/rule_set.rb:47
  def value=(value); end
end

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:13
CssParser::RuleSet::FONT_STYLE_PROPERTIES = T.let(T.unsafe(nil), Array)

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:14
CssParser::RuleSet::FONT_WEIGHT_PROPERTIES = T.let(T.unsafe(nil), Array)

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:36
CssParser::RuleSet::IMPORTANT = T.let(T.unsafe(nil), String)

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:12
CssParser::RuleSet::LIST_STYLE_PROPERTIES = T.let(T.unsafe(nil), Array)

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:34
CssParser::RuleSet::LPAREN = T.let(T.unsafe(nil), String)

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:19
CssParser::RuleSet::NUMBER_OF_DIMENSIONS = T.let(T.unsafe(nil), Integer)

# Patterns for specificity calculations
#
# pkg:gem/css_parser#lib/css_parser/rule_set.rb:8
CssParser::RuleSet::RE_ELEMENTS_AND_PSEUDO_ELEMENTS = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:9
CssParser::RuleSet::RE_NON_ID_ATTRIBUTES_AND_PSEUDO_CLASSES = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:35
CssParser::RuleSet::RPAREN = T.let(T.unsafe(nil), String)

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:33
CssParser::RuleSet::SEMICOLON = T.let(T.unsafe(nil), String)

# pkg:gem/css_parser#lib/css_parser/rule_set.rb:29
CssParser::RuleSet::WHITESPACE_REPLACEMENT = T.let(T.unsafe(nil), String)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:49
CssParser::STRIP_CSS_COMMENTS_RX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:50
CssParser::STRIP_HTML_COMMENTS_RX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:24
CssParser::URI_RX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/regexps.rb:25
CssParser::URI_RX_OR_NONE = T.let(T.unsafe(nil), Regexp)

# pkg:gem/css_parser#lib/css_parser/version.rb:4
CssParser::VERSION = T.let(T.unsafe(nil), String)
