# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sin_lru_redux` gem.
# Please instead update this file by running `bin/tapioca gem sin_lru_redux`.


# pkg:gem/sin_lru_redux#lib/lru_redux/version.rb:3
module LruRedux; end

# pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:4
class LruRedux::Cache
  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:7
  def initialize(*args); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:63
  def [](key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:71
  def []=(key, val); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:99
  def clear; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:103
  def count; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:89
  def delete(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:75
  def each(&block); end

  # Used further up the chain, non thread safe each
  #
  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:79
  def each_unsafe(&block); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:92
  def evict(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:52
  def fetch(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:39
  def getset(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:97
  def has_key?(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:5
  def ignore_nil; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:32
  def ignore_nil=(new_ignore_nil); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:94
  def key?(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:106
  def length; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:5
  def max_size; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:21
  def max_size=(new_max_size); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:107
  def size; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:81
  def to_a; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:28
  def ttl=(_); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:85
  def values; end

  private

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:140
  def evict_excess; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:145
  def evict_nil; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:158
  def store_item(key, val); end

  # For cache validation only, ensure all is valid
  #
  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:112
  def valid?; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:131
  def validate_ignore_nil!(ignore_nil); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/cache.rb:116
  def validate_max_size!(max_size); end
end

# pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:4
module LruRedux::TTL; end

# pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:5
class LruRedux::TTL::Cache
  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:8
  def initialize(*args); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:80
  def [](key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:92
  def []=(key, val); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:132
  def clear; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:137
  def count; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:117
  def delete(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:98
  def each(&block); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:103
  def each_unsafe(&block); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:123
  def evict(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:145
  def expire; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:65
  def fetch(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:48
  def getset(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:130
  def has_key?(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:6
  def ignore_nil; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:41
  def ignore_nil=(new_ignore_nil); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:125
  def key?(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:142
  def length; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:6
  def max_size; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:26
  def max_size=(new_max_size); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:143
  def size; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:105
  def to_a; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:6
  def ttl; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:34
  def ttl=(new_ttl); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:111
  def values; end

  private

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:194
  def evict_excess; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:201
  def evict_expired; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:213
  def evict_nil; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:226
  def store_item(key, value); end

  # For cache validation only, ensure all is valid
  #
  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:152
  def valid?; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:188
  def validate_ignore_nil!(ignore_nil); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:156
  def validate_max_size!(max_size); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/cache.rb:171
  def validate_ttl!(ttl); end
end

# pkg:gem/sin_lru_redux#lib/lru_redux/ttl/thread_safe_cache.rb:5
class LruRedux::TTL::ThreadSafeCache < ::LruRedux::TTL::Cache
  include ::MonitorMixin
  include ::LruRedux::Util::SafeSync

  # pkg:gem/sin_lru_redux#lib/lru_redux/ttl/thread_safe_cache.rb:8
  def expire; end
end

# pkg:gem/sin_lru_redux#lib/lru_redux/thread_safe_cache.rb:4
class LruRedux::ThreadSafeCache < ::LruRedux::Cache
  include ::MonitorMixin
  include ::LruRedux::Util::SafeSync
end

# pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:6
module LruRedux::Util; end

# pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:7
module LruRedux::Util::SafeSync
  include ::MonitorMixin

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:10
  def initialize(*args); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:44
  def [](key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:50
  def []=(key, value); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:98
  def clear; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:104
  def count; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:74
  def delete(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:56
  def each; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:80
  def evict(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:38
  def fetch(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:32
  def getset(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:92
  def has_key?(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:26
  def ignore_nil=(ignore_nil); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:86
  def key?(key); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:110
  def length; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:14
  def max_size=(max_size); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:116
  def size; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:62
  def to_a; end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:20
  def ttl=(ttl); end

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:68
  def values; end

  private

  # pkg:gem/sin_lru_redux#lib/lru_redux/util/safe_sync.rb:124
  def valid?; end
end

# pkg:gem/sin_lru_redux#lib/lru_redux/version.rb:4
LruRedux::VERSION = T.let(T.unsafe(nil), String)
