# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tailwindcss-rails` gem.
# Please instead update this file by running `bin/tapioca gem tailwindcss-rails`.


# pkg:gem/tailwindcss-rails#lib/tailwindcss-rails.rb:1
module Tailwindcss; end

# pkg:gem/tailwindcss-rails#lib/tailwindcss/commands.rb:4
module Tailwindcss::Commands
  class << self
    # pkg:gem/tailwindcss-rails#lib/tailwindcss/commands.rb:32
    def command_env(verbose:); end

    # pkg:gem/tailwindcss-rails#lib/tailwindcss/commands.rb:6
    def compile_command(debug: T.unsafe(nil), silent: T.unsafe(nil), **kwargs); end

    # pkg:gem/tailwindcss-rails#lib/tailwindcss/commands.rb:38
    def rails_css_compressor?; end

    # pkg:gem/tailwindcss-rails#lib/tailwindcss/commands.rb:25
    def watch_command(always: T.unsafe(nil), **kwargs); end
  end
end

# pkg:gem/tailwindcss-rails#lib/tailwindcss/engine.rb:4
class Tailwindcss::Engine < ::Rails::Engine; end

# pkg:gem/tailwindcss-rails#lib/tailwindcss/engines.rb:2
module Tailwindcss::Engines
  class << self
    # pkg:gem/tailwindcss-rails#lib/tailwindcss/engines.rb:4
    def bundle; end
  end
end

# Runs a child process and forwards stop signals (INT/TERM) to it, blocking
# until it exits, so a process manager that signals this process directly
# (e.g. foreman) doesn't leave the child orphaned. Shaped like
# +Process.spawn+/+Kernel#system+: it takes an +env+ hash followed by the
# command.
#
# pkg:gem/tailwindcss-rails#lib/tailwindcss/process_runner.rb:7
module Tailwindcss::ProcessRunner
  class << self
    # Spawn +command+ with +env+ and block until it exits, forwarding INT
    # (Ctrl-C) and TERM (e.g. foreman shutdown) to it so a process manager
    # that signals us directly doesn't leave an orphaned child behind.
    # Restores the previous signal handlers before returning so the
    # process-global traps aren't left changed. Returns the name of the signal
    # that was received (e.g. "TERM"), or nil if the child exited on its own.
    #
    # pkg:gem/tailwindcss-rails#lib/tailwindcss/process_runner.rb:19
    def spawn_and_wait(env, *command); end
  end
end

# Signals we forward to the spawned process so it shuts down with us instead
# of being orphaned.
#
# pkg:gem/tailwindcss-rails#lib/tailwindcss/process_runner.rb:10
Tailwindcss::ProcessRunner::FORWARDED_SIGNALS = T.let(T.unsafe(nil), Array)

# pkg:gem/tailwindcss-rails#lib/tailwindcss/version.rb:2
Tailwindcss::VERSION = T.let(T.unsafe(nil), String)
