# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `view_component` gem.
# Please instead update this file by running `bin/tapioca gem view_component`.


# pkg:gem/view_component#lib/view_component/base.rb:18
module ActionView; end

class ActionView::DependencyTracker
  extend ::ViewComponent::CacheDigest::DependencyTracking
end

# pkg:gem/view_component#lib/view_component/base.rb:19
class ActionView::OutputBuffer
  # pkg:gem/view_component#lib/view_component/base.rb:20
  def with_buffer(buf = T.unsafe(nil)); end
end

# pkg:gem/view_component#lib/view_component/version.rb:3
module ViewComponent
  extend ::ActiveSupport::Autoload
end

# pkg:gem/view_component#lib/view_component/errors.rb:226
class ViewComponent::AlreadyDefinedPolymorphicSlotSetterError < ::StandardError
  # pkg:gem/view_component#lib/view_component/errors.rb:231
  def initialize(setter_method_name, setter_name); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:227
ViewComponent::AlreadyDefinedPolymorphicSlotSetterError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/base.rb:32
class ViewComponent::Base
  include ::ActiveSupport::Benchmarkable
  include ::ActionView::Helpers::ActiveModelHelper
  include ::ActionView::Helpers::AssetUrlHelper
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper
  include ::ActionView::Helpers::AssetTagHelper
  include ::ActionView::Helpers::AtomFeedHelper
  include ::ActionView::Helpers::CacheHelper
  include ::ActionView::Helpers::ContentExfiltrationPreventionHelper
  include ::ActionView::Helpers::UrlHelper
  include ::ActionView::Helpers::SanitizeHelper
  include ::ActionView::Helpers::ControllerHelper
  include ::ActionView::Helpers::CspHelper
  include ::ActionView::Helpers::CsrfHelper
  include ::ActionView::Helpers::DateHelper
  include ::ActionView::Helpers::DebugHelper
  include ::ActionView::Helpers::TextHelper
  include ::ActionView::Helpers::FormTagHelper
  include ::ActionView::ModelNaming
  include ::ActionView::RecordIdentifier
  include ::ActionView::Helpers::FormHelper
  include ::ActionView::Helpers::TranslationHelper
  include ::ActionView::Helpers::FormOptionsHelper
  include ::ActionView::Helpers::JavaScriptHelper
  include ::ActionView::Helpers::NumberHelper
  include ::ActionView::Helpers::RenderingHelper
  include ::ActionView::Helpers
  include ::ERB::Escape
  include ::ActiveSupport::CoreExt::ERBUtil
  include ::ViewComponent::InlineTemplate
  include ::ViewComponent::Slotable
  include ::ViewComponent::Translatable
  include ::ViewComponent::WithContentHelper
  extend ::ActionView::Helpers::UrlHelper::ClassMethods
  extend ::ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ::ViewComponent::InlineTemplate::ClassMethods
  extend ::ViewComponent::Slotable::ClassMethods
  extend ::ViewComponent::Translatable::ClassMethods

  # Including `Rails.application.routes.url_helpers` defines an initializer that accepts (...),
  # so we have to define our own empty initializer to overwrite it.
  #
  # pkg:gem/view_component#lib/view_component/base.rb:95
  def initialize; end

  # pkg:gem/view_component#lib/view_component/base.rb:56
  def __vc_i18n_backend; end

  # pkg:gem/view_component#lib/view_component/base.rb:74
  def __vc_original_view_context; end

  # pkg:gem/view_component#lib/view_component/base.rb:74
  def __vc_original_view_context=(_arg0); end

  # @private
  #
  # pkg:gem/view_component#lib/view_component/base.rb:386
  def __vc_request; end

  # Called around rendering the component. Override to wrap the rendering of a
  # component in custom instrumentation, etc.
  #
  # @return [void]
  #
  # pkg:gem/view_component#lib/view_component/base.rb:252
  def around_render; end

  # Called before rendering the component. Override to perform operations that
  # depend on having access to the view context, such as helpers.
  #
  # @return [void]
  #
  # pkg:gem/view_component#lib/view_component/base.rb:244
  def before_render; end

  # Sync @output_buffer with the view context's current output buffer before
  # capturing. Form helpers create builders with @template_object pointing to
  # the component. When those builders later call capture inside a partial
  # (whose _run allocated a fresh OutputBuffer on the view context), the
  # component's stale @output_buffer would capture from the wrong buffer.
  # Temporarily switching to the view context's buffer keeps both in sync.
  #
  # @private
  #
  # pkg:gem/view_component#lib/view_component/base.rb:305
  def capture(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/view_component#lib/view_component/base.rb:60
  def config(*_arg0, **_arg1, &_arg2); end

  # The content passed to the component instance as a block.
  #
  # @return [String]
  #
  # pkg:gem/view_component#lib/view_component/base.rb:394
  def content; end

  # Whether `content` has been passed to the component.
  #
  # @return [Boolean]
  #
  # pkg:gem/view_component#lib/view_component/base.rb:411
  def content?; end

  # pkg:gem/view_component#lib/view_component/base.rb:69
  def content_security_policy_nonce(*_arg0, **_arg1, &_arg2); end

  # The current controller. Use sparingly as doing so introduces coupling
  # that inhibits encapsulation & reuse, often making testing difficult.
  #
  # @return [ActionController::Base]
  #
  # pkg:gem/view_component#lib/view_component/base.rb:317
  def controller; end

  # pkg:gem/view_component#lib/view_component/base.rb:75
  def current_template; end

  # pkg:gem/view_component#lib/view_component/base.rb:49
  def debug_missing_translation; end

  # pkg:gem/view_component#lib/view_component/base.rb:49
  def debug_missing_translation=(val); end

  # pkg:gem/view_component#lib/view_component/base.rb:60
  def form_authenticity_token(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/view_component#lib/view_component/base.rb:66
  def formats(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/view_component#lib/view_component/base.rb:66
  def formats=(arg); end

  # A proxy through which to access helpers. Use sparingly as doing so introduces
  # coupling that inhibits encapsulation & reuse, often making testing difficult.
  #
  # @return [ActionView::Base]
  #
  # pkg:gem/view_component#lib/view_component/base.rb:327
  def helpers; end

  # pkg:gem/view_component#lib/view_component/base.rb:63
  def lookup_context(*_arg0, **_arg1, &_arg2); end

  # @private
  #
  # pkg:gem/view_component#lib/view_component/base.rb:342
  def method_missing(method_name, *args); end

  # pkg:gem/view_component#lib/view_component/base.rb:63
  def output_buffer(*_arg0, **_arg1, &_arg2); end

  # Optional content to be returned after the rendered template.
  #
  # @return [String]
  #
  # pkg:gem/view_component#lib/view_component/base.rb:236
  def output_postamble; end

  # Optional content to be returned before the rendered template.
  #
  # @return [String]
  #
  # pkg:gem/view_component#lib/view_component/base.rb:229
  def output_preamble; end

  # pkg:gem/view_component#lib/view_component/base.rb:60
  def protect_against_forgery?(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/view_component#lib/view_component/base.rb:55
  def registered_slots; end

  # pkg:gem/view_component#lib/view_component/base.rb:55
  def registered_slots=(_arg0); end

  # pkg:gem/view_component#lib/view_component/base.rb:55
  def registered_slots?; end

  # Re-use original view_context if we're not rendering a component.
  #
  # As of v4, ViewComponent::Base re-uses the existing view context created
  # by ActionView, meaning the current view context and the original view
  # context are the same object. set_original_view_context is still called
  # to maintain backwards compatibility.
  #
  # @private
  #
  # pkg:gem/view_component#lib/view_component/base.rb:271
  def render(options = T.unsafe(nil), args = T.unsafe(nil), &block); end

  # Override to determine whether the ViewComponent should render.
  #
  # @return [Boolean]
  #
  # pkg:gem/view_component#lib/view_component/base.rb:259
  def render?; end

  # Entrypoint for rendering components.
  #
  # - `view_context`: ActionView context from calling view
  # - `block`: optional block to be captured within the view context
  #
  # Returns HTML that has been escaped by the respective template handler.
  #
  # @return [String]
  #
  # pkg:gem/view_component#lib/view_component/base.rb:106
  def render_in(view_context, **_arg1, &block); end

  # Subclass components that call `super` inside their template code will cause a
  # double render if they emit the result.
  #
  # ```erb
  # <%= super %> # double-renders
  # <% super %> # doesn't double-render
  # ```
  #
  # `super` also doesn't consider the current variant. `render_parent` renders the
  # parent template considering the current variant and emits the result without
  # double-rendering.
  #
  # pkg:gem/view_component#lib/view_component/base.rb:198
  def render_parent; end

  # Renders the parent component to a string and returns it. This method is meant
  # to be used inside custom #call methods when a string result is desired, eg.
  #
  # ```ruby
  # def call
  #   "<div>#{render_parent_to_string}</div>"
  # end
  # ```
  #
  # When rendering the parent inside an .erb template, use `#render_parent` instead.
  #
  # pkg:gem/view_component#lib/view_component/base.rb:213
  def render_parent_to_string; end

  # The current request. Use sparingly as doing so introduces coupling that
  # inhibits encapsulation & reuse, often making testing difficult.
  #
  # @return [ActionDispatch::Request]
  #
  # pkg:gem/view_component#lib/view_component/base.rb:381
  def request; end

  # Components render in their own view context. Helpers and other functionality
  # require a reference to the original Rails view context, an instance of
  # `ActionView::Base`. Use this method to set a reference to the original
  # view context. Objects that implement this method will render in the component's
  # view context, while objects that don't will render in the original view context
  # so helpers, etc work as expected.
  #
  # @param view_context [ActionView::Base] The original view context.
  #
  # @return [void]
  #
  # pkg:gem/view_component#lib/view_component/base.rb:87
  def set_original_view_context(view_context); end

  # For caching, such as #cache_if
  # @private
  #
  # pkg:gem/view_component#lib/view_component/base.rb:365
  def view_cache_dependencies; end

  # pkg:gem/view_component#lib/view_component/base.rb:63
  def view_flow(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/view_component#lib/view_component/base.rb:63
  def view_renderer(*_arg0, **_arg1, &_arg2); end

  # Exposes .virtual_path as an instance method
  #
  # @private
  #
  # pkg:gem/view_component#lib/view_component/base.rb:359
  def virtual_path; end

  # @private
  # Temporarily sets the virtual path to the captured value, then restores it.
  # This ensures translations and other path-dependent code execute with the correct scope.
  #
  # pkg:gem/view_component#lib/view_component/base.rb:418
  def with_captured_virtual_path(captured_path); end

  private

  # Raises when a component instance is rendered more than once.
  # Reusing a component instance across renders can leak request-scoped state
  # (controller, helpers, request, view_flow, slot content, `with_content`)
  # from an earlier render into a later one. See
  # `ViewComponent::ReusedInstanceError` and GHSA-8qw7-6phv-7q6p.
  #
  # pkg:gem/view_component#lib/view_component/base.rb:493
  def __vc_check_reused_instance!; end

  # pkg:gem/view_component#lib/view_component/base.rb:434
  def __vc_content_set_by_with_content_defined?; end

  # pkg:gem/view_component#lib/view_component/base.rb:438
  def __vc_maybe_escape_html(text); end

  # pkg:gem/view_component#lib/view_component/base.rb:430
  def __vc_render_in_block_provided?; end

  # pkg:gem/view_component#lib/view_component/base.rb:482
  def __vc_reset_render_state!; end

  # pkg:gem/view_component#lib/view_component/base.rb:462
  def __vc_safe_around_render_output(output); end

  # pkg:gem/view_component#lib/view_component/base.rb:456
  def __vc_safe_output_postamble; end

  # pkg:gem/view_component#lib/view_component/base.rb:450
  def __vc_safe_output_preamble; end

  # pkg:gem/view_component#lib/view_component/base.rb:428
  def view_context; end

  class << self
    # @private
    #
    # pkg:gem/view_component#lib/view_component/base.rb:773
    def __vc_collection_counter_parameter; end

    # @private
    #
    # pkg:gem/view_component#lib/view_component/base.rb:783
    def __vc_collection_iteration_parameter; end

    # @private
    #
    # pkg:gem/view_component#lib/view_component/base.rb:768
    def __vc_collection_parameter; end

    # @private
    #
    # pkg:gem/view_component#lib/view_component/base.rb:638
    def __vc_compile(raise_errors: T.unsafe(nil), force: T.unsafe(nil)); end

    # @private
    #
    # pkg:gem/view_component#lib/view_component/base.rb:686
    def __vc_compiled?; end

    # @private
    #
    # pkg:gem/view_component#lib/view_component/base.rb:706
    def __vc_compiler; end

    # @private
    #
    # pkg:gem/view_component#lib/view_component/base.rb:778
    def __vc_counter_argument_present?; end

    # @private
    #
    # pkg:gem/view_component#lib/view_component/base.rb:701
    def __vc_ensure_compiled; end

    # pkg:gem/view_component#lib/view_component/base.rb:56
    def __vc_i18n_backend; end

    # pkg:gem/view_component#lib/view_component/base.rb:56
    def __vc_i18n_backend=(value); end

    # @private
    #
    # pkg:gem/view_component#lib/view_component/base.rb:788
    def __vc_iteration_argument_present?; end

    # pkg:gem/view_component#lib/view_component/base.rb:72
    def __vc_strip_trailing_whitespace; end

    # pkg:gem/view_component#lib/view_component/base.rb:72
    def __vc_strip_trailing_whitespace=(value); end

    # Ensure the component initializer accepts the
    # collection parameter. By default, we don't
    # validate that the default parameter name
    # is accepted, as support for collection
    # rendering is optional.
    # @private
    #
    # pkg:gem/view_component#lib/view_component/base.rb:748
    def __vc_validate_collection_parameter!(validate_default: T.unsafe(nil)); end

    # Ensure the component initializer doesn't define
    # invalid parameters that could override the framework's
    # methods.
    # @private
    #
    # pkg:gem/view_component#lib/view_component/base.rb:761
    def __vc_validate_initialization_parameters!; end

    # Hook called by the compiler after a component is compiled.
    #
    # Extensions can override this class method to run logic after
    # compilation (e.g., generate helpers, register metadata, etc.).
    #
    # By default, this is a no-op.
    #
    # pkg:gem/view_component#lib/view_component/base.rb:696
    def after_compile; end

    # Returns the current config.
    #
    # @return [ActiveSupport::OrderedOptions]
    #
    # pkg:gem/view_component#lib/view_component/base.rb:39
    def config; end

    # pkg:gem/view_component#lib/view_component/base.rb:49
    def debug_missing_translation; end

    # pkg:gem/view_component#lib/view_component/base.rb:49
    def debug_missing_translation=(val); end

    # pkg:gem/view_component#lib/view_component/base.rb:34
    def generate(*_arg0, **_arg1, &_arg2); end

    # The file path of the component Ruby file.
    #
    # @return [String]
    # @private
    #
    # pkg:gem/view_component#lib/view_component/base.rb:573
    def identifier; end

    # The file path of the component Ruby file.
    #
    # @return [String]
    # @private
    #
    # pkg:gem/view_component#lib/view_component/base.rb:576
    def identifier=(_arg0); end

    # @private
    #
    # pkg:gem/view_component#lib/view_component/base.rb:643
    def inherited(child); end

    # pkg:gem/view_component#lib/view_component/base.rb:34
    def instrumentation_enabled(*_arg0, **_arg1, &_arg2); end

    # pkg:gem/view_component#lib/view_component/base.rb:34
    def previews(*_arg0, **_arg1, &_arg2); end

    # pkg:gem/view_component#lib/view_component/base.rb:55
    def registered_slots; end

    # pkg:gem/view_component#lib/view_component/base.rb:55
    def registered_slots=(value); end

    # pkg:gem/view_component#lib/view_component/base.rb:55
    def registered_slots?; end

    # Find sidecar files for the given extensions.
    #
    # The provided array of extensions is expected to contain
    # strings starting without the dot, example: `["erb", "haml"]`.
    #
    # For example, one might collect sidecar CSS files that need to be compiled.
    # @param extensions [Array<String>] Extensions of which to return matching sidecar files.
    #
    # pkg:gem/view_component#lib/view_component/base.rb:588
    def sidecar_files(extensions); end

    # Strips trailing whitespace from templates before compiling them.
    #
    # ```ruby
    # class MyComponent < ViewComponent::Base
    #   strip_trailing_whitespace
    # end
    # ```
    #
    # @param value [Boolean] Whether to strip newlines.
    #
    # pkg:gem/view_component#lib/view_component/base.rb:731
    def strip_trailing_whitespace(value = T.unsafe(nil)); end

    # Whether trailing whitespace will be stripped before compilation.
    #
    # @return [Boolean]
    #
    # pkg:gem/view_component#lib/view_component/base.rb:738
    def strip_trailing_whitespace?; end

    # @private
    #
    # pkg:gem/view_component#lib/view_component/base.rb:579
    def virtual_path; end

    # @private
    #
    # pkg:gem/view_component#lib/view_component/base.rb:579
    def virtual_path=(_arg0); end

    # Render a component for each element in a collection ([documentation](/guide/collections)):
    #
    # ```ruby
    # render(ProductsComponent.with_collection(@products, foo: :bar))
    # ```
    #
    # @param collection [Enumerable] A list of items to pass the ViewComponent one at a time.
    # @param spacer_component [ViewComponent::Base] Component instance to be rendered between items.
    # @param args [Arguments] Arguments to pass to the ViewComponent every time.
    #
    # pkg:gem/view_component#lib/view_component/base.rb:633
    def with_collection(collection, spacer_component: T.unsafe(nil), **args); end

    # Set the parameter name used when rendering elements of a collection ([documentation](/guide/collections)):
    #
    # ```ruby
    # with_collection_parameter :item
    # ```
    #
    # @param parameter [Symbol] The parameter name used when rendering elements of a collection.
    #
    # pkg:gem/view_component#lib/view_component/base.rb:717
    def with_collection_parameter(parameter); end

    private

    # pkg:gem/view_component#lib/view_component/base.rb:56
    def __class_attr___vc_i18n_backend; end

    # pkg:gem/view_component#lib/view_component/base.rb:56
    def __class_attr___vc_i18n_backend=(new_value); end

    # pkg:gem/view_component#lib/view_component/base.rb:72
    def __class_attr___vc_strip_trailing_whitespace; end

    # pkg:gem/view_component#lib/view_component/base.rb:72
    def __class_attr___vc_strip_trailing_whitespace=(new_value); end

    # pkg:gem/view_component#lib/view_component/base.rb:55
    def __class_attr_registered_slots; end

    # pkg:gem/view_component#lib/view_component/base.rb:55
    def __class_attr_registered_slots=(new_value); end

    # pkg:gem/view_component#lib/view_component/base.rb:798
    def __vc_initialize_parameter_names; end

    # pkg:gem/view_component#lib/view_component/base.rb:807
    def __vc_initialize_parameters; end

    # pkg:gem/view_component#lib/view_component/base.rb:811
    def __vc_provided_collection_parameter; end

    # pkg:gem/view_component#lib/view_component/base.rb:794
    def __vc_splatted_keyword_argument_present?; end
  end
end

# Resets every render-scoped instance variable derived from the calling view
# context so a reused instance cannot leak controller/helper/request/format
# state from a previous render. Slot state (`@__vc_set_slots`,
# `@__vc_content_set_by_with_content`) is intentionally preserved because it
# is populated by callers _before_ `render_in` runs (e.g. via `with_*`
# slot setters or `with_content`); reuse of an instance that has slot or
# `with_content` state is guarded against separately by
# `__vc_check_reused_instance!`.
#
# pkg:gem/view_component#lib/view_component/base.rb:476
ViewComponent::Base::RENDER_STATE_IVARS = T.let(T.unsafe(nil), Array)

# pkg:gem/view_component#lib/view_component/errors.rb:2
class ViewComponent::BaseError < ::StandardError
  # pkg:gem/view_component#lib/view_component/errors.rb:3
  def initialize; end
end

# Integrates ViewComponents into Rails' template digest tree.
#
# Rails computes a digest for every template from its source and the templates
# it renders. That digest is mixed into the key of every `<% cache %>` block in
# the template, so editing a partial busts the caches of everything that
# renders it.
#
# Components are invisible to that mechanism for two reasons:
#
# 1. **Discovery** — `ActionView::DependencyTracker` doesn't recognize
#    `render SomeComponent.new(...)` as a dependency.
# 2. **Resolution** — component templates live outside the view paths, and a
#    component's rendered output depends on its Ruby class and sidecar files,
#    not just its template.
#
# This module fixes both, reusing Rails' own `ActionView::Digestor` rather than
# reimplementing static analysis. Components opt in individually by including
# `ViewComponent::ExperimentallyCacheable`; until at least one component does,
# every hook here short-circuits.
#
# @private
#
# pkg:gem/view_component#lib/view_component/cache_digest.rb:29
module ViewComponent::CacheDigest
  extend ::ActiveSupport::Autoload

  class << self
    # Resolve a synthetic virtual path back to the component that owns it.
    #
    # @return [Class, nil]
    #
    # pkg:gem/view_component#lib/view_component/cache_digest.rb:94
    def component_for(virtual_path); end

    # Scan arbitrary source (a template or a component's Ruby file) for
    # renders of cacheable components.
    #
    # @return [Array<String>] synthetic virtual paths
    #
    # pkg:gem/view_component#lib/view_component/cache_digest.rb:119
    def component_paths_in(source); end

    # A lookup context for digesting components outside a request, where no
    # view context (and therefore no finder) exists.
    #
    # @return [ActionView::LookupContext]
    #
    # pkg:gem/view_component#lib/view_component/cache_digest.rb:201
    def default_finder; end

    # Scan a template's source for renders of cacheable components.
    #
    # Called for every template Rails digests, so it exits early when the
    # feature is unused.
    #
    # @return [Array<String>] synthetic virtual paths
    #
    # pkg:gem/view_component#lib/view_component/cache_digest.rb:109
    def dependencies_in(template); end

    # Compute the digest of a component using Rails' digest tree.
    #
    # @param component [Class] a component that includes `ExperimentallyCacheable`
    # @param finder [ActionView::LookupContext]
    # @param format [Symbol]
    # @return [String]
    #
    # pkg:gem/view_component#lib/view_component/cache_digest.rb:190
    def digest(component, finder: T.unsafe(nil), format: T.unsafe(nil)); end

    # @return [Boolean] whether any component has opted in.
    #
    # pkg:gem/view_component#lib/view_component/cache_digest.rb:71
    def enabled?; end

    # Resolve `# Template Dependency: SomeComponent` declarations.
    #
    # Rails' escape hatch takes a template path, but the path a component is
    # digested under is an internal detail. Naming the class instead keeps
    # that detail out of application code, so `SomeComponent` is translated
    # to the path the Digestor can resolve.
    #
    # @return [Array<Array(String, String)>] pairs of declared name and
    #   synthetic virtual path
    #
    # pkg:gem/view_component#lib/view_component/cache_digest.rb:173
    def explicit_component_dependencies(source); end

    # Wire the tracker and resolver into Action View.
    #
    # Called each time a component includes `ExperimentallyCacheable`. Both
    # steps below are individually idempotent, so no "already installed" flag
    # is kept. Both hooks short-circuit while the registry is empty, so
    # applications that never opt in are unaffected.
    #
    # @private
    #
    # pkg:gem/view_component#lib/view_component/cache_digest.rb:214
    def install!; end

    # Scan a component's Ruby source for partials referenced by string path,
    # such as `render "posts/byline"` inside a `#call` method.
    #
    # Uses Rails' own render parser — the same one `RubyTracker` runs over
    # compiled templates — rather than a second implementation of the same
    # analysis. Its results are then narrowed to paths that appear verbatim in
    # the source, which keeps string literals and discards the speculative
    # `things/_thing` entries the parser infers from dynamic renders like
    # `render @thing` or `render FooComponent.new`. Those would resolve to
    # nothing and only add log noise; components rendered from Ruby are
    # already found precisely by `component_paths_in`.
    #
    # @param source [String] Ruby source
    # @param name [String] virtual path the source is being digested under
    # @return [Array<String>] partial virtual paths
    #
    # pkg:gem/view_component#lib/view_component/cache_digest.rb:143
    def partial_paths_in(source, name); end

    # @private
    #
    # pkg:gem/view_component#lib/view_component/cache_digest.rb:76
    def register(component); end

    # Virtual paths of components that have opted into caching, mapped to
    # their class names.
    #
    # Class *names* rather than class objects so the registry survives
    # autoloader reloads without pinning stale constants in memory.
    #
    # @return [Hash{String => String}]
    #
    # pkg:gem/view_component#lib/view_component/cache_digest.rb:66
    def registry; end

    # Action View has shipped its render parser as a class (Rails 7.1, and
    # again on main) and as a module holding a `Default` implementation
    # chosen from Prism or Ripper (Rails 7.2 through 8.1).
    #
    # @param parser [Class, Module] `ActionView::RenderParser`
    # @return [Class]
    #
    # pkg:gem/view_component#lib/view_component/cache_digest.rb:160
    def resolve_render_parser(parser); end

    # The synthetic virtual path a component is digested under.
    #
    # @return [String, nil]
    #
    # pkg:gem/view_component#lib/view_component/cache_digest.rb:85
    def virtual_path_for(component); end

    private

    # Resolve a constant name to a component that opted into caching.
    #
    # Returns nil for anything else, including constants that don't exist.
    # Autoloading here is safe: the template is about to render this constant
    # anyway.
    #
    # pkg:gem/view_component#lib/view_component/cache_digest.rb:231
    def constantize_component(constant_name); end
  end
end

# Teaches `ActionView::DependencyTracker` to see components.
#
# Prepended to the tracker's singleton class rather than to a specific
# tracker implementation (`ERBTracker`, `RubyTracker`, or the trackers
# registered by the Haml and Slim gems). `find_dependencies` is the single
# seam every tracker flows through, so hooking it here works regardless of
# which handler a template uses and doesn't depend on tracker internals.
#
# @private
#
# pkg:gem/view_component#lib/view_component/cache_digest/dependency_tracking.rb:16
module ViewComponent::CacheDigest::DependencyTracking
  # pkg:gem/view_component#lib/view_component/cache_digest/dependency_tracking.rb:17
  def find_dependencies(name, template, view_paths = T.unsafe(nil)); end

  class << self
    # @private
    #
    # pkg:gem/view_component#lib/view_component/cache_digest/dependency_tracking.rb:38
    def install!; end
  end
end

# Rails' escape hatch for dependencies static analysis can't see.
#
# pkg:gem/view_component#lib/view_component/cache_digest.rb:57
ViewComponent::CacheDigest::EXPLICIT_DEPENDENCY = T.let(T.unsafe(nil), Regexp)

# Matches `render FooComponent`, `render(Foo::BarComponent.new(...))`,
# `render FooComponent.with_collection(...)`, etc.
#
# Deliberately a plain source scan rather than a tracker-specific hook: it
# behaves identically for the ERB tracker, the Prism-based Ruby tracker, and
# third-party Haml/Slim trackers.
#
# pkg:gem/view_component#lib/view_component/cache_digest.rb:47
ViewComponent::CacheDigest::RENDER_CALL = T.let(T.unsafe(nil), Regexp)

# Resolved once at load time rather than memoized, so no class-level state
# is written after boot.
#
# pkg:gem/view_component#lib/view_component/cache_digest.rb:245
ViewComponent::CacheDigest::RENDER_PARSER = ActionView::RenderParser::PrismRenderParser

# Synthesizes the templates Rails' `ActionView::Digestor` digests components from.
#
# Once `DependencyTracking` reports `view_component/cache_digest/foo_component`
# as a dependency, the Digestor tries to find a template at that path. No such
# file exists: a component's rendered output depends on its template *and* its
# Ruby class, its sidecar files, and its superclasses.
#
# This resolver answers with a synthetic template whose source encodes all of
# those inputs. The template is never compiled or rendered; the Digestor only
# reads `#source` to hash it and to scan it for further dependencies.
#
# @private
#
# pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:17
class ViewComponent::CacheDigest::Resolver < ::ActionView::Resolver
  # pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:48
  def ==(other); end

  # pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:45
  def eql?(other); end

  # pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:27
  def find_templates(name, prefix, partial, details, locals = T.unsafe(nil)); end

  # pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:43
  def to_path; end

  # pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:40
  def to_s; end

  private

  # pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:52
  def build_template(component, virtual_path, details); end

  # The component and any component superclasses, nearest first. Including
  # ancestors means editing `ApplicationComponent` invalidates every
  # component that inherits from it.
  #
  # pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:99
  def component_ancestors(component); end

  # pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:133
  def explicit_dependencies(component); end

  # pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:168
  def file_digest(path); end

  # Everything a component renders from Ruby code rather than from a
  # template. Action View's trackers only read templates, so a `#call`
  # method that renders another component or a partial would otherwise go
  # unnoticed.
  #
  # pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:151
  def ruby_dependencies(component); end

  # pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:161
  def ruby_sources(component); end

  # pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:107
  def source_files(component); end

  # The synthetic source. Every section exists to change this string when
  # something the component renders from changes.
  #
  # pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:65
  def source_for(component); end

  # pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:113
  def template_files(component); end

  # Sidecar template files plus inline templates, which live in the Ruby
  # file and so are invisible to Action View's trackers.
  #
  # pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:122
  def template_sources(component); end

  class << self
    # pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:22
    def instance; end
  end
end

# Built once at load time rather than memoized, so no class-level state
# is written after boot. The resolver is stateless: it reads from disk on
# every call so it can't go stale when a component changes.
#
# pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:175
ViewComponent::CacheDigest::Resolver::INSTANCE = T.let(T.unsafe(nil), ViewComponent::CacheDigest::Resolver)

# Extensions whose contents are hashed into the synthetic source.
#
# pkg:gem/view_component#lib/view_component/cache_digest/resolver.rb:19
ViewComponent::CacheDigest::Resolver::SIDECAR_EXTENSIONS = T.let(T.unsafe(nil), Array)

# Prefix for the synthetic virtual paths components are digested under.
#
# Namespaced under `view_component/` so it can't collide with an
# application partial.
#
# pkg:gem/view_component#lib/view_component/cache_digest.rb:39
ViewComponent::CacheDigest::VIRTUAL_PATH_PREFIX = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/errors.rb:236
class ViewComponent::CacheDigestTemplateError < ::StandardError
  # pkg:gem/view_component#lib/view_component/errors.rb:243
  def initialize(component_name); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:237
ViewComponent::CacheDigestTemplateError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/collection.rb:7
class ViewComponent::Collection
  include ::Enumerable
  include ::ActionView::Helpers::OutputSafetyHelper

  # pkg:gem/view_component#lib/view_component/collection.rb:50
  def initialize(component, object, spacer_component, **options); end

  # pkg:gem/view_component#lib/view_component/collection.rb:11
  def component; end

  # pkg:gem/view_component#lib/view_component/collection.rb:22
  def each(&block); end

  # pkg:gem/view_component#lib/view_component/collection.rb:15
  def render_in(view_context, **_, &block); end

  # pkg:gem/view_component#lib/view_component/collection.rb:13
  def size(*_arg0, **_arg1, &_arg2); end

  private

  # pkg:gem/view_component#lib/view_component/collection.rb:57
  def collection_variable(object); end

  # pkg:gem/view_component#lib/view_component/collection.rb:65
  def component_options(item, iterator); end

  # Always rebuild child component instances per render to avoid leaking
  # request-scoped state from a previous render into a later one (GHSA).
  #
  # pkg:gem/view_component#lib/view_component/collection.rb:38
  def components; end

  # Render the spacer through a fresh `dup` so a collection rendered multiple
  # times does not reuse (and trip the single-render guard on) the spacer
  # instance passed by the caller.
  #
  # pkg:gem/view_component#lib/view_component/collection.rb:77
  def rendered_spacer(view_context); end
end

# Keeps track of which templates have already been compiled
# This isn't part of the public API
#
# pkg:gem/view_component#lib/view_component/compile_cache.rb:6
module ViewComponent::CompileCache
  private

  # pkg:gem/view_component#lib/view_component/compile_cache.rb:17
  def compiled?(klass); end

  # pkg:gem/view_component#lib/view_component/compile_cache.rb:25
  def invalidate!; end

  # pkg:gem/view_component#lib/view_component/compile_cache.rb:21
  def invalidate_class!(klass); end

  # pkg:gem/view_component#lib/view_component/compile_cache.rb:13
  def register(klass); end

  class << self
    # pkg:gem/view_component#lib/view_component/compile_cache.rb:7
    def cache; end

    # pkg:gem/view_component#lib/view_component/compile_cache.rb:7
    def cache=(val); end

    # pkg:gem/view_component#lib/view_component/compile_cache.rb:17
    def compiled?(klass); end

    # pkg:gem/view_component#lib/view_component/compile_cache.rb:25
    def invalidate!; end

    # pkg:gem/view_component#lib/view_component/compile_cache.rb:21
    def invalidate_class!(klass); end

    # pkg:gem/view_component#lib/view_component/compile_cache.rb:13
    def register(klass); end
  end
end

# pkg:gem/view_component#lib/view_component/compiler.rb:6
class ViewComponent::Compiler
  # pkg:gem/view_component#lib/view_component/compiler.rb:13
  def initialize(component); end

  # pkg:gem/view_component#lib/view_component/compiler.rb:11
  def __vc_development_mode; end

  # pkg:gem/view_component#lib/view_component/compiler.rb:11
  def __vc_development_mode=(_arg0); end

  # pkg:gem/view_component#lib/view_component/compiler.rb:11
  def __vc_development_mode?; end

  # pkg:gem/view_component#lib/view_component/compiler.rb:22
  def compile(raise_errors: T.unsafe(nil), force: T.unsafe(nil)); end

  # pkg:gem/view_component#lib/view_component/compiler.rb:18
  def compiled?; end

  # @param requested_details [ActionView::TemplateDetails::Requested] i.e. locales, formats, variants
  #
  # @return all matching compiled templates, in priority order based on the requested details from LookupContext
  #
  # pkg:gem/view_component#lib/view_component/compiler.rb:63
  def find_templates_for(requested_details); end

  private

  # pkg:gem/view_component#lib/view_component/compiler.rb:81
  def define_render_template_for; end

  # pkg:gem/view_component#lib/view_component/compiler.rb:170
  def gather_templates; end

  # pkg:gem/view_component#lib/view_component/compiler.rb:107
  def template_errors; end

  # pkg:gem/view_component#lib/view_component/compiler.rb:79
  def templates; end

  class << self
    # pkg:gem/view_component#lib/view_component/compiler.rb:11
    def __vc_development_mode; end

    # pkg:gem/view_component#lib/view_component/compiler.rb:11
    def __vc_development_mode=(value); end

    # pkg:gem/view_component#lib/view_component/compiler.rb:11
    def __vc_development_mode?; end

    private

    # pkg:gem/view_component#lib/view_component/compiler.rb:11
    def __class_attr___vc_development_mode; end

    # pkg:gem/view_component#lib/view_component/compiler.rb:11
    def __class_attr___vc_development_mode=(new_value); end
  end
end

# pkg:gem/view_component#lib/view_component/config.rb:6
class ViewComponent::Config
  # pkg:gem/view_component#lib/view_component/config.rb:185
  def initialize; end

  # pkg:gem/view_component#lib/view_component/config.rb:183
  def current; end

  # pkg:gem/view_component#lib/view_component/config.rb:183
  def current=(_arg0); end

  # pkg:gem/view_component#lib/view_component/config.rb:189
  def method_missing(method, *_arg1, **_arg2, &_arg3); end

  private

  # pkg:gem/view_component#lib/view_component/config.rb:193
  def config; end

  # pkg:gem/view_component#lib/view_component/config.rb:189
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end

  class << self
    # pkg:gem/view_component#lib/view_component/config.rb:183
    def current; end

    # pkg:gem/view_component#lib/view_component/config.rb:183
    def current=(value); end

    # `new` without any arguments initializes the default configuration, but
    # it's important to differentiate in case that's no longer the case in
    # future.
    #
    # pkg:gem/view_component#lib/view_component/config.rb:11
    def default(*_arg0); end

    # pkg:gem/view_component#lib/view_component/config.rb:158
    def default_generate_options; end

    # @!attribute instrumentation_enabled
    #
    # @return [Boolean]
    # Whether ActiveSupport notifications are enabled.
    # Defaults to `false`.
    #
    # pkg:gem/view_component#lib/view_component/config.rb:134
    def default_preview_paths; end

    # pkg:gem/view_component#lib/view_component/config.rb:165
    def default_previews_options; end

    # pkg:gem/view_component#lib/view_component/config.rb:144
    def default_rails_engines_preview_paths; end

    # pkg:gem/view_component#lib/view_component/config.rb:138
    def default_rails_preview_paths; end

    # pkg:gem/view_component#lib/view_component/config.rb:13
    def defaults; end

    # pkg:gem/view_component#lib/view_component/config.rb:152
    def registered_rails_engines_with_previews; end

    private

    # pkg:gem/view_component#lib/view_component/config.rb:183
    def __class_attr_current; end

    # pkg:gem/view_component#lib/view_component/config.rb:183
    def __class_attr_current=(new_value); end
  end
end

# pkg:gem/view_component#lib/view_component/errors.rb:168
class ViewComponent::ContentAlreadySetForPolymorphicSlotError < ::StandardError
  # pkg:gem/view_component#lib/view_component/errors.rb:171
  def initialize(slot_name); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:169
ViewComponent::ContentAlreadySetForPolymorphicSlotError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/errors.rb:258
class ViewComponent::ContentPassedToCachedComponentError < ::StandardError
  # pkg:gem/view_component#lib/view_component/errors.rb:266
  def initialize(component_name); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:259
ViewComponent::ContentPassedToCachedComponentError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/errors.rb:96
class ViewComponent::ContentSlotNameError < ::StandardError
  # pkg:gem/view_component#lib/view_component/errors.rb:102
  def initialize(klass_name); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:97
ViewComponent::ContentSlotNameError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/errors.rb:213
class ViewComponent::ControllerCalledBeforeRenderError < ::ViewComponent::BaseError; end

# pkg:gem/view_component#lib/view_component/errors.rb:214
ViewComponent::ControllerCalledBeforeRenderError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/deprecation.rb:6
ViewComponent::DEPRECATION_HORIZON = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/deprecation.rb:7
ViewComponent::Deprecation = T.let(T.unsafe(nil), ActiveSupport::Deprecation)

# pkg:gem/view_component#lib/view_component/errors.rb:57
class ViewComponent::DuplicateContentError < ::StandardError
  # pkg:gem/view_component#lib/view_component/errors.rb:63
  def initialize(klass_name); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:58
ViewComponent::DuplicateContentError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/errors.rb:8
class ViewComponent::DuplicateSlotContentError < ::StandardError
  # pkg:gem/view_component#lib/view_component/errors.rb:14
  def initialize(klass_name); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:9
ViewComponent::DuplicateSlotContentError::MESSAGE = T.let(T.unsafe(nil), String)

# Experimental caching support for ViewComponents.
#
# **This API is experimental.** It may change or be removed in a non-major
# release. Please share feedback in
# https://github.com/ViewComponent/view_component/issues/234.
#
# Including this module does two things:
#
# 1. Registers the component with Rails' template digest tree, so a
#    `<% cache %>` block wrapping the component in a view is invalidated when
#    the component's template, Ruby class, sidecar files, or child components
#    change.
# 2. Enables the `cache_on` macro, which caches the component's own rendered
#    output.
#
# ```ruby
# class MessageComponent < ViewComponent::Base
#   include ViewComponent::ExperimentallyCacheable
#
#   cache_on :message
#
#   def initialize(message:)
#     @message = message
#   end
# end
# ```
#
# pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:32
module ViewComponent::ExperimentallyCacheable
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ViewComponent::ExperimentallyCacheable::ClassMethods

  # The cache key for this rendering of the component.
  #
  # Combines the component's identity, its source digest, the requested
  # format and variant, the current locale, and the values declared with
  # `cache_on`. Override for full control.
  #
  # @param view_context [ActionView::Base]
  # @return [String]
  #
  # pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:204
  def cache_key(view_context = T.unsafe(nil)); end

  # Renders the component, reading from and writing to the Rails cache when
  # `cache_on` has been declared.
  #
  # @private
  #
  # pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:169
  def render_in(view_context, **_arg1, &block); end

  private

  # pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:245
  def __vc_cache_conditions_met?; end

  # pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:237
  def __vc_cache_enabled?(view_context); end

  # pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:277
  def __vc_cache_format(lookup_context); end

  # pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:267
  def __vc_cache_on_values; end

  # pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:281
  def __vc_cache_variant(lookup_context); end

  # pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:257
  def __vc_evaluate_cache_condition(condition); end

  # Slots set by the caller via `with_*`. Checked before rendering, so slots
  # a component fills in for itself with a `default_*` method — which resolve
  # lazily during the render — aren't counted.
  #
  # pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:233
  def __vc_slots_set_by_caller?; end
end

# pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:45
module ViewComponent::ExperimentallyCacheable::ClassMethods
  # pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:108
  def __vc_cache_if; end

  # pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:103
  def __vc_cache_on; end

  # pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:115
  def __vc_cache_unless; end

  # pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:122
  def __vc_cacheable?; end

  # pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:129
  def __vc_caches_output?; end

  # pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:150
  def cache_digest(finder: T.unsafe(nil), format: T.unsafe(nil)); end

  # pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:75
  def cache_on(*methods, **options, &block); end

  # pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:159
  def inherited(child); end
end

# Stands in for `nil` in the cache key. Without it, `expand_cache_key`
# renders `nil` and `""` identically, so two components differing only in
# that respect would share an entry.
#
# pkg:gem/view_component#lib/view_component/experimentally_cacheable.rb:38
ViewComponent::ExperimentallyCacheable::NIL_CACHE_VALUE = T.let(T.unsafe(nil), Symbol)

# pkg:gem/view_component#lib/view_component/errors.rb:204
class ViewComponent::HelpersCalledBeforeRenderError < ::ViewComponent::BaseError; end

# pkg:gem/view_component#lib/view_component/errors.rb:205
ViewComponent::HelpersCalledBeforeRenderError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/inline_template.rb:4
module ViewComponent::InlineTemplate
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ViewComponent::InlineTemplate::ClassMethods
end

# pkg:gem/view_component#lib/view_component/inline_template.rb:9
module ViewComponent::InlineTemplate::ClassMethods
  # pkg:gem/view_component#lib/view_component/inline_template.rb:41
  def __vc_inline_template; end

  # pkg:gem/view_component#lib/view_component/inline_template.rb:45
  def __vc_inline_template_language; end

  # pkg:gem/view_component#lib/view_component/inline_template.rb:49
  def inherited(subclass); end

  # pkg:gem/view_component#lib/view_component/inline_template.rb:10
  def method_missing(method, *args); end

  private

  # pkg:gem/view_component#lib/view_component/inline_template.rb:37
  def respond_to_missing?(method, include_all = T.unsafe(nil)); end
end

# pkg:gem/view_component#lib/view_component/inline_template.rb:7
class ViewComponent::InlineTemplate::Template < ::Struct
  # pkg:gem/view_component#lib/view_component/inline_template.rb:7
  def language; end

  # pkg:gem/view_component#lib/view_component/inline_template.rb:7
  def language=(_); end

  # pkg:gem/view_component#lib/view_component/inline_template.rb:7
  def lineno; end

  # pkg:gem/view_component#lib/view_component/inline_template.rb:7
  def lineno=(_); end

  # pkg:gem/view_component#lib/view_component/inline_template.rb:7
  def path; end

  # pkg:gem/view_component#lib/view_component/inline_template.rb:7
  def path=(_); end

  # pkg:gem/view_component#lib/view_component/inline_template.rb:7
  def source; end

  # pkg:gem/view_component#lib/view_component/inline_template.rb:7
  def source=(_); end

  class << self
    # pkg:gem/view_component#lib/view_component/inline_template.rb:7
    def [](*_arg0); end

    # pkg:gem/view_component#lib/view_component/inline_template.rb:7
    def inspect; end

    # pkg:gem/view_component#lib/view_component/inline_template.rb:7
    def keyword_init?; end

    # pkg:gem/view_component#lib/view_component/inline_template.rb:7
    def members; end

    # pkg:gem/view_component#lib/view_component/inline_template.rb:7
    def new(*_arg0); end
  end
end

# pkg:gem/view_component#lib/view_component/instrumentation.rb:6
module ViewComponent::Instrumentation
  # pkg:gem/view_component#lib/view_component/instrumentation.rb:32
  def around_render; end

  # pkg:gem/view_component#lib/view_component/instrumentation.rb:11
  def render_in(*_arg0, **_arg1, &_arg2); end

  class << self
    # pkg:gem/view_component#lib/view_component/instrumentation.rb:7
    def included(mod); end
  end
end

# pkg:gem/view_component#lib/view_component/errors.rb:90
class ViewComponent::InvalidCollectionArgumentError < ::ViewComponent::BaseError; end

# pkg:gem/view_component#lib/view_component/errors.rb:91
ViewComponent::InvalidCollectionArgumentError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/errors.rb:107
class ViewComponent::InvalidSlotDefinitionError < ::ViewComponent::BaseError; end

# pkg:gem/view_component#lib/view_component/errors.rb:108
ViewComponent::InvalidSlotDefinitionError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/errors.rb:113
class ViewComponent::InvalidSlotNameError < ::StandardError; end

# pkg:gem/view_component#lib/view_component/errors.rb:68
class ViewComponent::MissingCollectionArgumentError < ::StandardError
  # pkg:gem/view_component#lib/view_component/errors.rb:75
  def initialize(klass_name, parameter); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:69
ViewComponent::MissingCollectionArgumentError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/errors.rb:31
class ViewComponent::MissingPreviewTemplateError < ::StandardError
  # pkg:gem/view_component#lib/view_component/errors.rb:36
  def initialize(example); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:32
ViewComponent::MissingPreviewTemplateError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/errors.rb:41
class ViewComponent::MissingTemplateError < ::StandardError
  # pkg:gem/view_component#lib/view_component/errors.rb:46
  def initialize(component, request_detail); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:42
ViewComponent::MissingTemplateError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/errors.rb:27
class ViewComponent::MultipleInlineTemplatesError < ::ViewComponent::BaseError; end

# pkg:gem/view_component#lib/view_component/errors.rb:28
ViewComponent::MultipleInlineTemplatesError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/errors.rb:176
class ViewComponent::NilWithContentError < ::ViewComponent::BaseError; end

# pkg:gem/view_component#lib/view_component/errors.rb:177
ViewComponent::NilWithContentError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/preview.rb:6
class ViewComponent::Preview
  include ::ActionView::Helpers::AssetUrlHelper
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper
  include ::ActionView::Helpers::AssetTagHelper
  extend ::ActiveSupport::DescendantsTracker

  # pkg:gem/view_component#lib/view_component/preview.rb:16
  def render(component, **args, &block); end

  # pkg:gem/view_component#lib/view_component/preview.rb:26
  def render_with_template(template: T.unsafe(nil), locals: T.unsafe(nil)); end

  class << self
    # @private
    #
    # pkg:gem/view_component#lib/view_component/preview.rb:98
    def __vc_load_previews; end

    # Returns all component preview classes.
    #
    # pkg:gem/view_component#lib/view_component/preview.rb:35
    def all; end

    # Returns all of the available examples for the component preview.
    #
    # pkg:gem/view_component#lib/view_component/preview.rb:55
    def examples; end

    # Returns +true+ if the preview exists.
    #
    # pkg:gem/view_component#lib/view_component/preview.rb:60
    def exists?(preview); end

    # Find a component preview by its underscored class name.
    #
    # pkg:gem/view_component#lib/view_component/preview.rb:65
    def find(preview); end

    # Setter for layout name.
    #
    # pkg:gem/view_component#lib/view_component/preview.rb:76
    def layout(layout_name); end

    # Returns the relative path (from preview_path) to the preview example template if the template exists
    #
    # pkg:gem/view_component#lib/view_component/preview.rb:82
    def preview_example_template_path(example); end

    # Returns the underscored name of the component preview without the suffix.
    #
    # pkg:gem/view_component#lib/view_component/preview.rb:70
    def preview_name; end

    # Returns the arguments for rendering of the component in its layout
    #
    # pkg:gem/view_component#lib/view_component/preview.rb:42
    def render_args(example, params: T.unsafe(nil)); end

    private

    # pkg:gem/view_component#lib/view_component/preview.rb:106
    def preview_paths; end
  end
end

# pkg:gem/view_component#lib/view_component/errors.rb:128
class ViewComponent::RedefinedSlotError < ::StandardError
  # pkg:gem/view_component#lib/view_component/errors.rb:133
  def initialize(klass_name, slot_name); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:129
ViewComponent::RedefinedSlotError::MESSAGE = T.let(T.unsafe(nil), String)

# LookupContext computes and encapsulates @details for each request
# so that it doesn't need to be recomputed on each partial render.
# This data is wrapped in ActionView::TemplateDetails::Requested and
# used by instances of ActionView::Resolver to choose which template
# best matches the request.
#
# ActionView considers this logic internal to template/partial resolution.
# We're exposing it to the compiler via `refine` so that ViewComponent
# can match Rails' template picking logic.
#
# pkg:gem/view_component#lib/view_component/request_details.rb:13
module ViewComponent::RequestDetails; end

# pkg:gem/view_component#lib/view_component/request_details.rb:14
ViewComponent::RequestDetails::EMPTY_DETAILS = T.let(T.unsafe(nil), Hash)

# pkg:gem/view_component#lib/view_component/errors.rb:80
class ViewComponent::ReservedParameterError < ::StandardError
  # pkg:gem/view_component#lib/view_component/errors.rb:85
  def initialize(klass_name, parameter); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:81
ViewComponent::ReservedParameterError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/errors.rb:148
class ViewComponent::ReservedPluralSlotNameError < ::ViewComponent::InvalidSlotNameError
  # pkg:gem/view_component#lib/view_component/errors.rb:153
  def initialize(klass_name, slot_name); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:149
ViewComponent::ReservedPluralSlotNameError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/errors.rb:138
class ViewComponent::ReservedSingularSlotNameError < ::ViewComponent::InvalidSlotNameError
  # pkg:gem/view_component#lib/view_component/errors.rb:143
  def initialize(klass_name, slot_name); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:139
ViewComponent::ReservedSingularSlotNameError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/errors.rb:182
class ViewComponent::ReusedInstanceError < ::StandardError
  # pkg:gem/view_component#lib/view_component/errors.rb:190
  def initialize(klass_name); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:183
ViewComponent::ReusedInstanceError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/serializable/proxy.rb:4
module ViewComponent::Serializable
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ViewComponent::Serializable::ClassMethods
end

# pkg:gem/view_component#lib/view_component/serializable.rb:12
module ViewComponent::Serializable::ClassMethods
  # pkg:gem/view_component#lib/view_component/serializable.rb:19
  def render_later(*args, **_arg1, &block); end
end

# A proxy that wraps a component class and its initialization arguments, deferring
# component instantiation until render time. This allows slot calls and other
# post-initialize configuration to be captured and replayed, and enables the
# proxy itself (rather than a live component instance) to be serialized for
# background jobs (e.g. ActiveJob / Turbo Streams).
#
# pkg:gem/view_component#lib/view_component/serializable/proxy.rb:10
class ViewComponent::Serializable::Proxy
  # pkg:gem/view_component#lib/view_component/serializable/proxy.rb:30
  def initialize(component_class, *args, **_arg2); end

  # pkg:gem/view_component#lib/view_component/serializable/proxy.rb:28
  def component_class; end

  # pkg:gem/view_component#lib/view_component/serializable/proxy.rb:28
  def initialize_args; end

  # pkg:gem/view_component#lib/view_component/serializable/proxy.rb:49
  def method_missing(method_name, *args, **_arg2, &block); end

  # Implements the Rails renderable interface
  #
  # pkg:gem/view_component#lib/view_component/serializable/proxy.rb:42
  def render_in(view_context, &block); end

  # Returns a hash that can be rebuilt into a Proxy instance using +deserialize+
  #
  # pkg:gem/view_component#lib/view_component/serializable/proxy.rb:63
  def serialize; end

  # pkg:gem/view_component#lib/view_component/serializable/proxy.rb:28
  def slot_calls; end

  private

  # pkg:gem/view_component#lib/view_component/serializable/proxy.rb:101
  def build_component; end

  # pkg:gem/view_component#lib/view_component/serializable/proxy.rb:92
  def capture_slot_call(method_name, args, &block); end

  # pkg:gem/view_component#lib/view_component/serializable/proxy.rb:58
  def respond_to_missing?(method_name, include_private = T.unsafe(nil)); end

  # pkg:gem/view_component#lib/view_component/serializable/proxy.rb:88
  def slot_method?(method_name); end

  class << self
    # Rebuilds a Proxy from a serialized hash produced by +serialize+
    #
    # pkg:gem/view_component#lib/view_component/serializable/proxy.rb:12
    def deserialize(hash); end
  end
end

# pkg:gem/view_component#lib/view_component/serializable.rb:10
class ViewComponent::Serializable::UnserializableError < ::ArgumentError; end

# pkg:gem/view_component#lib/view_component/slot.rb:6
class ViewComponent::Slot
  include ::ViewComponent::WithContentHelper

  # pkg:gem/view_component#lib/view_component/slot.rb:11
  def initialize(parent); end

  # pkg:gem/view_component#lib/view_component/slot.rb:9
  def __vc_component_instance=(_arg0); end

  # pkg:gem/view_component#lib/view_component/slot.rb:9
  def __vc_content=(_arg0); end

  # pkg:gem/view_component#lib/view_component/slot.rb:9
  def __vc_content_block=(_arg0); end

  # pkg:gem/view_component#lib/view_component/slot.rb:9
  def __vc_content_block_virtual_path=(_arg0); end

  # pkg:gem/view_component#lib/view_component/slot.rb:15
  def content?; end

  # pkg:gem/view_component#lib/view_component/slot.rb:103
  def html_safe?; end

  # Allow access to public component methods via the wrapper
  #
  # for example
  #
  # calling `header.name` (where `header` is a slot) will call `name`
  # on the `HeaderComponent` instance.
  #
  # Where the component may look like:
  #
  # class MyComponent < ViewComponent::Base
  #   has_one :header, HeaderComponent
  #
  #   class HeaderComponent < ViewComponent::Base
  #     def name
  #       @name
  #     end
  #   end
  # end
  #
  # pkg:gem/view_component#lib/view_component/slot.rb:99
  def method_missing(symbol, *args, **kwargs, &block); end

  # Used to render the slot content in the template
  #
  # There's currently 3 different values that may be set, that we can render.
  #
  # If the slot renderable is a component, the string class name of a
  # component, or a function that returns a component, we render that
  # component instance, returning the string.
  #
  # If the slot renderable is a function and returns a string, it's
  # set as `@__vc_content` and is returned directly.
  #
  # If there is no slot renderable, we evaluate the block passed to
  # the slot and return it.
  #
  # pkg:gem/view_component#lib/view_component/slot.rb:45
  def to_s; end

  # pkg:gem/view_component#lib/view_component/slot.rb:24
  def with_content(args); end

  private

  # pkg:gem/view_component#lib/view_component/slot.rb:113
  def __vc_component_instance?; end

  # pkg:gem/view_component#lib/view_component/slot.rb:107
  def respond_to_missing?(symbol, include_all = T.unsafe(nil)); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:116
class ViewComponent::SlotPredicateNameError < ::ViewComponent::InvalidSlotNameError
  # pkg:gem/view_component#lib/view_component/errors.rb:123
  def initialize(klass_name, slot_name); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:117
ViewComponent::SlotPredicateNameError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/slotable.rb:8
module ViewComponent::Slotable
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ViewComponent::Slotable::ClassMethods

  # pkg:gem/view_component#lib/view_component/slotable.rb:355
  def __vc_get_slot(slot_name); end

  # pkg:gem/view_component#lib/view_component/slotable.rb:446
  def __vc_set_polymorphic_slot(slot_name, poly_type = T.unsafe(nil), *args, **kwargs, &block); end

  # pkg:gem/view_component#lib/view_component/slotable.rb:380
  def __vc_set_slot(slot_name, slot_definition = T.unsafe(nil), *args, **kwargs, &block); end

  module GeneratedClassMethods
    def registered_slots; end
    def registered_slots=(value); end
    def registered_slots?; end
  end

  module GeneratedInstanceMethods
    def registered_slots; end
    def registered_slots=(value); end
    def registered_slots?; end
  end
end

# pkg:gem/view_component#lib/view_component/slotable.rb:21
module ViewComponent::Slotable::ClassMethods
  # pkg:gem/view_component#lib/view_component/slotable.rb:216
  def __vc_register_default_slots; end

  # pkg:gem/view_component#lib/view_component/slotable.rb:198
  def inherited(child); end

  # pkg:gem/view_component#lib/view_component/slotable.rb:144
  def renders_many(slot_name, callable = T.unsafe(nil)); end

  # pkg:gem/view_component#lib/view_component/slotable.rb:75
  def renders_one(slot_name, callable = T.unsafe(nil)); end

  # pkg:gem/view_component#lib/view_component/slotable.rb:187
  def slot_type(slot_name); end

  private

  # pkg:gem/view_component#lib/view_component/slotable.rb:283
  def __vc_define_slot(slot_name, collection:, callable:); end

  # pkg:gem/view_component#lib/view_component/slotable.rb:341
  def __vc_raise_if_slot_conflicts_with_call(slot_name); end

  # pkg:gem/view_component#lib/view_component/slotable.rb:337
  def __vc_raise_if_slot_ends_with_question_mark(slot_name); end

  # pkg:gem/view_component#lib/view_component/slotable.rb:347
  def __vc_raise_if_slot_name_uncountable(slot_name); end

  # pkg:gem/view_component#lib/view_component/slotable.rb:331
  def __vc_raise_if_slot_registered(slot_name); end

  # pkg:gem/view_component#lib/view_component/slotable.rb:231
  def __vc_register_polymorphic_slot(slot_name, types, collection:); end

  # pkg:gem/view_component#lib/view_component/slotable.rb:227
  def __vc_register_slot(slot_name, **kwargs); end

  # pkg:gem/view_component#lib/view_component/slotable.rb:306
  def __vc_validate_plural_slot_name(slot_name); end

  # pkg:gem/view_component#lib/view_component/slotable.rb:317
  def __vc_validate_singular_slot_name(slot_name); end
end

# pkg:gem/view_component#lib/view_component/slotable.rb:11
ViewComponent::Slotable::RESERVED_NAMES = T.let(T.unsafe(nil), Hash)

# pkg:gem/view_component#lib/view_component/errors.rb:222
class ViewComponent::SystemTestControllerNefariousPathError < ::ViewComponent::BaseError; end

# pkg:gem/view_component#lib/view_component/errors.rb:223
ViewComponent::SystemTestControllerNefariousPathError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/template.rb:4
class ViewComponent::Template
  # pkg:gem/view_component#lib/view_component/template.rb:15
  def initialize(component:, details:, lineno: T.unsafe(nil), path: T.unsafe(nil)); end

  # pkg:gem/view_component#lib/view_component/template.rb:181
  def call_method_name; end

  # pkg:gem/view_component#lib/view_component/template.rb:145
  def compile_to_component; end

  # pkg:gem/view_component#lib/view_component/template.rb:159
  def coverage_running?; end

  # pkg:gem/view_component#lib/view_component/template.rb:176
  def default_format?; end

  # pkg:gem/view_component#lib/view_component/template.rb:10
  def details; end

  # pkg:gem/view_component#lib/view_component/template.rb:13
  def format(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/view_component#lib/view_component/template.rb:179
  def html?; end

  # pkg:gem/view_component#lib/view_component/template.rb:172
  def inline_call?; end

  # pkg:gem/view_component#lib/view_component/template.rb:191
  def normalized_variant_name; end

  # pkg:gem/view_component#lib/view_component/template.rb:10
  def path; end

  # pkg:gem/view_component#lib/view_component/template.rb:168
  def requires_compiled_superclass?; end

  # pkg:gem/view_component#lib/view_component/template.rb:187
  def safe_method_name; end

  # pkg:gem/view_component#lib/view_component/template.rb:163
  def safe_method_name_call; end

  # pkg:gem/view_component#lib/view_component/template.rb:13
  def variant(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/view_component#lib/view_component/template.rb:12
  def virtual_path(*_arg0, **_arg1, &_arg2); end

  private

  # pkg:gem/view_component#lib/view_component/template.rb:199
  def compiled_source; end

  # pkg:gem/view_component#lib/view_component/template.rb:197
  def lineno; end
end

# pkg:gem/view_component#lib/view_component/template.rb:5
ViewComponent::Template::DEFAULT_FORMAT = T.let(T.unsafe(nil), Symbol)

# pkg:gem/view_component#lib/view_component/template.rb:8
class ViewComponent::Template::DataWithSource < ::Struct
  # pkg:gem/view_component#lib/view_component/template.rb:8
  def format; end

  # pkg:gem/view_component#lib/view_component/template.rb:8
  def format=(_); end

  # pkg:gem/view_component#lib/view_component/template.rb:8
  def identifier; end

  # pkg:gem/view_component#lib/view_component/template.rb:8
  def identifier=(_); end

  # pkg:gem/view_component#lib/view_component/template.rb:8
  def short_identifier; end

  # pkg:gem/view_component#lib/view_component/template.rb:8
  def short_identifier=(_); end

  # pkg:gem/view_component#lib/view_component/template.rb:8
  def type; end

  # pkg:gem/view_component#lib/view_component/template.rb:8
  def type=(_); end

  class << self
    # pkg:gem/view_component#lib/view_component/template.rb:8
    def [](*_arg0); end

    # pkg:gem/view_component#lib/view_component/template.rb:8
    def inspect; end

    # pkg:gem/view_component#lib/view_component/template.rb:8
    def keyword_init?; end

    # pkg:gem/view_component#lib/view_component/template.rb:8
    def members; end

    # pkg:gem/view_component#lib/view_component/template.rb:8
    def new(*_arg0); end
  end
end

# pkg:gem/view_component#lib/view_component/template.rb:22
class ViewComponent::Template::File < ::ViewComponent::Template
  # pkg:gem/view_component#lib/view_component/template.rb:23
  def initialize(component:, details:, path:); end

  # Load file each time we look up #source in case the file has been modified
  #
  # pkg:gem/view_component#lib/view_component/template.rb:39
  def source; end

  # pkg:gem/view_component#lib/view_component/template.rb:34
  def type; end

  private

  # pkg:gem/view_component#lib/view_component/template.rb:72
  def compiled_source; end

  # pkg:gem/view_component#lib/view_component/template.rb:68
  def erb_newline_compensation_needed?; end

  # Rails 8.1 added a newline to compiled ERB output (rails/rails#53731).
  # Use -1 to compensate for correct line numbers in stack traces.
  # However, negative line numbers cause segfaults when Ruby's coverage
  # is enabled (bugs.ruby-lang.org/issues/19363). In that case, strip the
  # annotation line from compiled source instead.
  #
  # Computed at compile time rather than at initialization because both
  # coverage and annotation settings can change between the two.
  #
  # pkg:gem/view_component#lib/view_component/template.rb:53
  def lineno; end

  # Strip the annotation line to maintain correct line numbers when coverage
  # is running (avoids segfault from negative lineno)
  #
  # pkg:gem/view_component#lib/view_component/template.rb:62
  def strip_annotation_line?; end
end

# pkg:gem/view_component#lib/view_component/template.rb:79
class ViewComponent::Template::Inline < ::ViewComponent::Template
  # pkg:gem/view_component#lib/view_component/template.rb:82
  def initialize(component:, inline_template:); end

  # pkg:gem/view_component#lib/view_component/template.rb:80
  def source; end

  # pkg:gem/view_component#lib/view_component/template.rb:106
  def type; end
end

# pkg:gem/view_component#lib/view_component/template.rb:111
class ViewComponent::Template::InlineCall < ::ViewComponent::Template
  # pkg:gem/view_component#lib/view_component/template.rb:112
  def initialize(component:, method_name:, defined_on_self:); end

  # pkg:gem/view_component#lib/view_component/template.rb:126
  def compile_to_component; end

  # pkg:gem/view_component#lib/view_component/template.rb:140
  def defined_on_self?; end

  # pkg:gem/view_component#lib/view_component/template.rb:130
  def safe_method_name_call; end

  # pkg:gem/view_component#lib/view_component/template.rb:122
  def type; end
end

# pkg:gem/view_component#lib/view_component/errors.rb:19
class ViewComponent::TemplateError < ::StandardError
  # pkg:gem/view_component#lib/view_component/errors.rb:20
  def initialize(errors, templates = T.unsafe(nil)); end
end

# pkg:gem/view_component#lib/view_component/translatable.rb:8
module ViewComponent::Translatable
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ViewComponent::Translatable::ClassMethods

  # pkg:gem/view_component#lib/view_component/translatable.rb:124
  def __vc_i18n_scope; end

  # pkg:gem/view_component#lib/view_component/translatable.rb:122
  def t(key = T.unsafe(nil), **options); end

  # pkg:gem/view_component#lib/view_component/translatable.rb:93
  def translate(key = T.unsafe(nil), **options); end

  private

  # pkg:gem/view_component#lib/view_component/translatable.rb:141
  def __vc_html_escape_translation_options!(options); end

  # pkg:gem/view_component#lib/view_component/translatable.rb:130
  def __vc_html_safe_translation(translation); end

  module GeneratedClassMethods
    def __vc_i18n_backend; end
    def __vc_i18n_backend=(value); end
  end

  module GeneratedInstanceMethods
    def __vc_i18n_backend; end
  end
end

# pkg:gem/view_component#lib/view_component/translatable.rb:21
module ViewComponent::Translatable::ClassMethods
  # pkg:gem/view_component#lib/view_component/translatable.rb:26
  def __vc_build_i18n_backend; end

  # pkg:gem/view_component#lib/view_component/translatable.rb:46
  def __vc_i18n_key(key, scope = T.unsafe(nil)); end

  # pkg:gem/view_component#lib/view_component/translatable.rb:22
  def __vc_i18n_scope; end

  # pkg:gem/view_component#lib/view_component/translatable.rb:65
  def t(key = T.unsafe(nil), **options); end

  # pkg:gem/view_component#lib/view_component/translatable.rb:54
  def translate(key = T.unsafe(nil), **options); end
end

# pkg:gem/view_component#lib/view_component/translatable.rb:11
ViewComponent::Translatable::HTML_SAFE_TRANSLATION_KEY = T.let(T.unsafe(nil), Regexp)

# pkg:gem/view_component#lib/view_component/translatable.rb:68
class ViewComponent::Translatable::I18nBackend < ::I18n::Backend::Simple
  # pkg:gem/view_component#lib/view_component/translatable.rb:71
  def initialize(scope:, load_paths:); end

  # Ensure the Simple backend won't load paths from ::I18n.load_path
  #
  # pkg:gem/view_component#lib/view_component/translatable.rb:77
  def load_translations; end

  # pkg:gem/view_component#lib/view_component/translatable.rb:81
  def scope_data(data); end

  # pkg:gem/view_component#lib/view_component/translatable.rb:88
  def store_translations(locale, data, options = T.unsafe(nil)); end
end

# pkg:gem/view_component#lib/view_component/translatable.rb:69
ViewComponent::Translatable::I18nBackend::EMPTY_HASH = T.let(T.unsafe(nil), Hash)

# pkg:gem/view_component#lib/view_component/translatable.rb:14
ViewComponent::Translatable::TRANSLATION_EXTENSIONS = T.let(T.unsafe(nil), Array)

# pkg:gem/view_component#lib/view_component/errors.rb:195
class ViewComponent::TranslateCalledBeforeRenderError < ::ViewComponent::BaseError; end

# pkg:gem/view_component#lib/view_component/errors.rb:196
ViewComponent::TranslateCalledBeforeRenderError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/errors.rb:158
class ViewComponent::UncountableSlotNameError < ::ViewComponent::InvalidSlotNameError
  # pkg:gem/view_component#lib/view_component/errors.rb:163
  def initialize(klass_name, slot_name); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:159
ViewComponent::UncountableSlotNameError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/errors.rb:248
class ViewComponent::UndefinedCacheKeyMethodError < ::StandardError
  # pkg:gem/view_component#lib/view_component/errors.rb:253
  def initialize(component_name, method_name); end
end

# pkg:gem/view_component#lib/view_component/errors.rb:249
ViewComponent::UndefinedCacheKeyMethodError::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/version.rb:4
module ViewComponent::VERSION; end

# pkg:gem/view_component#lib/view_component/version.rb:5
ViewComponent::VERSION::MAJOR = T.let(T.unsafe(nil), Integer)

# pkg:gem/view_component#lib/view_component/version.rb:6
ViewComponent::VERSION::MINOR = T.let(T.unsafe(nil), Integer)

# pkg:gem/view_component#lib/view_component/version.rb:7
ViewComponent::VERSION::PATCH = T.let(T.unsafe(nil), Integer)

# pkg:gem/view_component#lib/view_component/version.rb:8
ViewComponent::VERSION::PRE = T.let(T.unsafe(nil), T.untyped)

# pkg:gem/view_component#lib/view_component/version.rb:10
ViewComponent::VERSION::STRING = T.let(T.unsafe(nil), String)

# pkg:gem/view_component#lib/view_component/with_content_helper.rb:4
module ViewComponent::WithContentHelper
  # pkg:gem/view_component#lib/view_component/with_content_helper.rb:5
  def with_content(value); end
end
