# frozen_string_literal: true

# 生成物整合スペック(層4 — 07-testing §6)。パイプラインの健全性を検証する。
require "rails_helper"
require "digest"
require "yaml"

GENERATED_DIR = File.join(REPO_ROOT, "lib/shadcn_view_components/generated/contracts")
GEN_JSON_DIR = File.join(REPO_ROOT, "gen/contracts")
CSS_FILE = File.join(REPO_ROOT, "app/assets/stylesheets/shadcn/shadcn.css")

RSpec.describe "generated outputs integrity", type: :conformance do
  describe "AUTO-GENERATED headers" do
    it "every generated Ruby file declares itself auto-generated and typed strict" do
      files = Dir[File.join(GENERATED_DIR, "*.rb")]
      expect(files).not_to be_empty

      files.each do |file|
        content = File.read(file)
        expect(content).to start_with("# typed: strict")
        expect(content).to include("# !! AUTO-GENERATED by tools/extractor — DO NOT EDIT !!")
        expect(content).to include("Regenerate with: rake shadcn:generate")
      end
    end

    it "the generated CSS declares itself auto-generated" do
      expect(File.read(CSS_FILE)).to start_with("/* !! AUTO-GENERATED by tools/extractor — DO NOT EDIT !! */")
    end
  end

  describe "contract JSON ↔ Ruby module parity" do
    it "generates one Ruby file per contract JSON, with matching exports" do
      json_files = Dir[File.join(GEN_JSON_DIR, "*.json")].map { |f| File.basename(f, ".json") }.sort
      ruby_files = Dir[File.join(GENERATED_DIR, "*.rb")].map { |f| File.basename(f, ".rb") }.sort

      expect(ruby_files).to eq(json_files)

      json_files.each do |name|
        contract = JSON.parse(File.read(File.join(GEN_JSON_DIR, "#{name}.json")))
        contract["exports"].each_value do |export_data|
          contract_path = export_data.fetch("component_class").delete_prefix("Shadcn::")
          ruby_module = ShadcnViewComponents::Contracts.const_get(contract_path)

          expect(ruby_module::ROOT_SLOT).to eq(export_data.fetch("root_slot"))
          expect(ruby_module::COMBINATIONS.size).to eq(export_data.fetch("combinations").size)
          expect(ruby_module::SLOTS.map { |slot| slot[:name] }.sort).to eq(export_data.fetch("slots").map { |slot| slot["name"] }.sort)
        end
      end
    end
  end

  describe "theme CSS contents" do
    it "contains the class-based dark variant and semantic tokens" do
      css = File.read(CSS_FILE)
      expect(css).to include("@custom-variant dark (&:is(.dark *));")
      expect(css).to include(":root {")
      expect(css).to include(".dark {")
      expect(css).to include("--background:")
      expect(css).to include("--color-background: var(--background);")
      expect(css).to include("--radius-lg: var(--radius);")
    end
  end

  describe "manifest integrity (手編集の検知)" do
    it "matches items.*.sha256 against the vendored files" do
      manifest = JSON.parse(File.read(File.join(REPO_ROOT, "vendor/shadcn/manifest.json")))

      expect(manifest.fetch("version")).to eq(2)
      expect(manifest.dig("source", "registry_snapshot", "consistency")).to eq("double-fetch")

      manifest["items"].each do |name, entry|
        path = File.join(REPO_ROOT, "vendor/shadcn", entry["path"])
        expect(Digest::SHA256.file(path).hexdigest).to eq(entry["sha256"]), "#{name} does not match its manifest sha256"
      end

      theme_path = File.join(REPO_ROOT, "vendor/shadcn", manifest.dig("theme", "path"))
      expect(Digest::SHA256.file(theme_path).hexdigest).to eq(manifest.dig("theme", "sha256"))

      %w[index style].each do |artifact|
        entry = manifest.dig("source", "registry_snapshot")
        path = File.join(REPO_ROOT, "vendor/shadcn", entry.fetch("#{artifact}_path"))
        expect(Digest::SHA256.file(path).hexdigest).to eq(entry.fetch("#{artifact}_sha256"))
      end
    end
  end

  describe "registry coverage (vendor itemの実装済み・非対応分類 — 07 §6)" do
    let(:manifest_items) do
      JSON.parse(File.read(File.join(REPO_ROOT, "vendor/shadcn/manifest.json")))["items"].keys.sort
    end
    let(:registry) { YAML.safe_load_file(File.expand_path("../conformance/registry.yml", __dir__)) }

    it "covers every vendored item as implemented or unsupported" do
      uncovered = manifest_items - registry.keys
      expect(uncovered).to be_empty, "items missing from spec/conformance/registry.yml: #{uncovered.join(', ')}"
    end

    it "does not reference items that no longer exist upstream" do
      stale = registry.keys - manifest_items
      expect(stale).to be_empty, "stale registry entries for removed upstream items: #{stale.join(', ')}"
    end

    it "has a resolvable component class and contract for implemented entries" do
      registry.select { |_name, entry| entry.key?("exports") }.each do |name, entry|
        entry.fetch("exports").each do |export_entry|
          component_name = export_entry.fetch("component")
          expect { component_name.constantize }.not_to raise_error, "#{name}/#{export_entry['export']}: component class missing"
          contract_path = component_name.delete_prefix("Shadcn::")
          expect(ShadcnViewComponents::Contracts.const_defined?(contract_path)).to be(true),
                                                                                   "#{name}/#{export_entry['export']}: contract missing"
        end
      end
    end

    it "keeps registry, extractor targets, and generated contracts in sync" do
      targets = JSON.parse(File.read(File.join(REPO_ROOT, "tools/extractor/config/targets.json")))["items"].sort
      implemented = registry.select { |_name, entry| entry.key?("exports") }.keys.sort
      generated = Dir[File.join(GEN_JSON_DIR, "*.json")].map { |f| File.basename(f, ".json") }.sort

      # 個別評価ルートのアイテム(upstream が静的抽出の対象外)。契約は
      # lib/shadcn_view_components/contracts/<name>.rb に手動で保守される
      individual = Dir[File.join(REPO_ROOT, "lib/shadcn_view_components/contracts/*.rb")]
                   .map { |f| File.basename(f, ".rb") }.sort

      expect(implemented).to eq((targets + individual).uniq.sort),
                             "registry.yml と targets.json + 個別契約が乖離している"
      expect(generated).to eq(targets), "gen/contracts と targets.json が乖離している"
    end
  end
end
